project_id = "schdyxcunwcvddlcshwd"

[functions.daily-room]
verify_jwt = false

[functions.delete-account]
verify_jwt = false

[functions.email-verification]
verify_jwt = false

[functions.event-notifications]
verify_jwt = false

[functions.vibe-notification]
verify_jwt = false

[functions.verify-admin]
verify_jwt = false

[functions.geocode]
verify_jwt = false

[functions.phone-verify]
verify_jwt = true

[functions.email-drip]
verify_jwt = false

[functions.unsubscribe]
verify_jwt = false

[functions.admin-review-verification]
verify_jwt = false

[functions.create-video-upload]
verify_jwt = false

[functions.video-webhook]
verify_jwt = false

[functions.delete-vibe-video]
verify_jwt = false

[functions.upload-image]
verify_jwt = false

[functions.upload-voice]
verify_jwt = false

[functions.upload-event-cover]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.create-event-checkout]
verify_jwt = false

[functions.create-credits-checkout]
verify_jwt = false
