project_id = "schdyxcunwcvddlcshwd"

[functions.daily-room]
verify_jwt = false

[functions.delete-account]
verify_jwt = false

[functions.email-verification]
verify_jwt = false

[functions.event-notifications]
verify_jwt = false

[functions.vibe-notification]
verify_jwt = false

[functions.verify-admin]
verify_jwt = false

[functions.geocode]
verify_jwt = false

[functions.phone-verify]
verify_jwt = false
