/**
 * Video Date screen styles. Extracted verbatim from `app/date/[id].tsx`
 * (VD rebuild PR 8).
 */
import { StyleSheet } from "react-native";
import { fonts, spacing } from "@/constants/theme";

export const styles = StyleSheet.create({
  container: { flex: 1 },
  center: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 24,
  },
  message: { fontSize: 18, marginBottom: 16 },
  error: { fontSize: 16, textAlign: "center", marginBottom: 16 },
  errorBar: {
    position: "absolute",
    top: 100,
    left: 16,
    right: 16,
    padding: 12,
    borderRadius: 8,
  },
  errorBarText: { color: "#fff", textAlign: "center" },
  warmupChoiceNotice: {
    position: "absolute",
    left: 16,
    right: 16,
    zIndex: 90,
    elevation: 20,
    borderWidth: 1,
    borderRadius: 20,
    paddingVertical: 12,
    paddingLeft: 17,
    paddingRight: 14,
    flexDirection: "row",
    alignItems: "flex-start",
    overflow: "hidden",
    shadowColor: "hsl(263, 70%, 66%)",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.22,
    shadowRadius: 22,
  },
  warmupChoiceNoticeRail: {
    position: "absolute",
    left: 0,
    top: 12,
    bottom: 12,
    width: 4,
    borderRadius: 999,
  },
  warmupChoiceNoticeIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(139,92,246,0.24)",
    backgroundColor: "rgba(139,92,246,0.16)",
    alignItems: "center",
    justifyContent: "center",
  },
  warmupChoiceNoticeCopy: { flex: 1, marginLeft: 12 },
  warmupChoiceNoticeTitle: { fontSize: 14, lineHeight: 18, fontWeight: "700" },
  warmupChoiceNoticeMessage: { marginTop: 3, fontSize: 12, lineHeight: 17 },
  extendBanner: {
    position: "absolute",
    top: 156,
    left: 16,
    right: 16,
    padding: 12,
    borderRadius: 10,
    borderWidth: 1,
  },
  extendBannerText: { textAlign: "center", fontSize: 14, fontWeight: "600" },
  nativeBackgroundBanner: {
    position: "absolute",
    top: 156,
    left: 16,
    right: 16,
    zIndex: 58,
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
  },
  nativeBackgroundTitle: {
    textAlign: "center",
    fontSize: 14,
    fontWeight: "700",
  },
  nativeBackgroundText: {
    marginTop: 3,
    textAlign: "center",
    fontSize: 12,
    lineHeight: 17,
  },
  button: { paddingVertical: 12, paddingHorizontal: 24, borderRadius: 8 },
  buttonText: { color: "#fff", fontSize: 16 },
  remoteContainer: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "#000",
  },
  remoteGlassWash: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.08)",
  },
  placeholderRemote: { justifyContent: "center", alignItems: "center" },
  placeholderText: { color: "#888", fontSize: 16 },
  localPip: {
    position: "absolute",
    top: 108,
    right: 16,
    width: 112,
    height: 154,
    borderRadius: 22,
    overflow: "hidden",
    borderWidth: 1.5,
    backgroundColor: "#000",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.48,
    shadowRadius: 28,
    elevation: 10,
  },
  localVideo: { width: "100%", height: "100%" },
  placeholderLocal: { justifyContent: "center", alignItems: "center" },
  muteBadge: {
    position: "absolute",
    top: 6,
    left: 6,
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "hsl(0, 84%, 60%)",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.28,
    shadowRadius: 14,
    elevation: 4,
  },
  flipCameraBadge: {
    position: "absolute",
    top: 6,
    right: 6,
    width: 30,
    height: 30,
    borderRadius: 15,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.28,
    shadowRadius: 14,
    elevation: 4,
  },
  localPipHandle: {
    position: "absolute",
    bottom: 8,
    left: "50%",
    width: 32,
    height: 4,
    marginLeft: -16,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.32)",
  },
  topBar: {
    position: "absolute",
    top: 50,
    left: 16,
    right: 16,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  topBarFullWidth: { width: "100%", alignItems: "center" },
  topChromeRow: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  partnerChip: {
    minHeight: 56,
    maxWidth: 172,
    flexShrink: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    borderRadius: 999,
    borderWidth: 1,
    paddingVertical: 7,
    paddingLeft: 8,
    paddingRight: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.36,
    shadowRadius: 24,
    elevation: 6,
  },
  partnerAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 1,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.08)",
  },
  partnerAvatarImage: {
    width: "100%",
    height: "100%",
  },
  partnerAvatarInitial: {
    fontSize: 15,
    fontWeight: "800",
  },
  partnerChipCopy: {
    minWidth: 0,
    flexShrink: 1,
    gap: 3,
  },
  partnerChipName: {
    fontSize: 15,
    fontWeight: "800",
  },
  partnerChipAge: {
    fontSize: 15,
    fontWeight: "500",
  },
  partnerStatusRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  liveDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
  },
  partnerStatusText: {
    fontSize: 11,
    fontWeight: "700",
  },
  timerCluster: {
    alignItems: "flex-end",
    flexShrink: 0,
    gap: 5,
  },
  stageTimerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  stagePill: {
    minHeight: 38,
    borderRadius: 999,
    borderWidth: 1,
    paddingVertical: 9,
    paddingHorizontal: 12,
    justifyContent: "center",
  },
  stagePillText: {
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 1.6,
    textTransform: "uppercase",
  },
  waitingTimerPill: {
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 22,
    backgroundColor: "rgba(0,0,0,0.5)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  waitingTimerText: { fontSize: 12, fontWeight: "700" },
  initialTimeoutWrap: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 55,
    paddingHorizontal: spacing.lg,
    backgroundColor: "rgba(0,0,0,0.88)",
  },
  initialTimeoutCard: {
    width: "100%",
    maxWidth: 360,
    borderWidth: 1,
    borderRadius: 18,
    padding: spacing.lg,
    gap: spacing.md,
  },
  initialTimeoutTitle: { fontSize: 17, fontWeight: "700" },
  initialTimeoutSub: { fontSize: 14, lineHeight: 20 },
  initialTimeoutActions: { gap: spacing.sm },
  initialRetryBtn: {
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  initialRetryText: { color: "#fff", fontSize: 15, fontWeight: "700" },
  initialBackBtn: {
    borderRadius: 12,
    borderWidth: 1,
    paddingVertical: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  initialBackText: { fontSize: 15, fontWeight: "600" },
  initialBtnPressed: { opacity: 0.85 },
  netHint: { fontSize: 11, fontWeight: "600" },
  entryBottomStack: {
    position: "absolute",
    left: 0,
    right: 0,
    alignItems: "center",
    paddingHorizontal: 24,
  },
  iceBreakerFloat: {
    position: "absolute",
    left: 0,
    right: 0,
    zIndex: 26,
    alignItems: "center",
    paddingHorizontal: 24,
  },
  iceBreakerCollapsed: {
    alignSelf: "flex-start",
    minHeight: 40,
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    borderWidth: 1,
    borderRadius: 999,
    paddingVertical: 9,
    paddingHorizontal: 14,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.28,
    shadowRadius: 22,
    elevation: 6,
  },
  iceBreakerCollapsedText: {
    fontSize: 12,
    fontFamily: fonts.display,
  },
  keepTheVibeWrap: {
    position: "absolute",
    top: 116,
    right: 16,
    alignItems: "flex-end",
  },
  controlsBar: { position: "absolute", bottom: 0, left: 0, right: 0 },
});
