import { supabase } from "@/integrations/supabase/client";

export type MyProfileSettingsRow = Record<string, unknown> & {
  id: string;
  updated_at?: string | null;
  created_at?: string | null;
  name?: string | null;
  birth_date?: string | null;
  age?: number | null;
  gender?: string | null;
  interested_in?: string[] | null;
  tagline?: string | null;
  height_cm?: number | null;
  location?: string | null;
  country?: string | null;
  job?: string | null;
  company?: string | null;
  about_me?: string | null;
  bio?: string | null;
  looking_for?: string | null;
  relationship_intent?: string | null;
  onboarding_complete?: boolean | null;
  onboarding_stage?: string | null;
  lifestyle?: Record<string, unknown> | null;
  prompts?: unknown[] | null;
  photos?: string[] | null;
  avatar_url?: string | null;
  bunny_video_uid?: string | null;
  bunny_video_status?: string | null;
  vibe_video_status?: string | null;
  vibe_caption?: string | null;
  vibe_video_captions?: unknown;
  photo_verified?: boolean | null;
  photo_verified_at?: string | null;
  photo_verification_expires_at?: string | null;
  phone_number?: string | null;
  phone_verified?: boolean | null;
  phone_verified_at?: string | null;
  email_verified?: boolean | null;
  verified_email?: string | null;
  is_premium?: boolean | null;
  premium_until?: string | null;
  subscription_tier?: string | null;
  vibe_score?: number | null;
  vibe_score_label?: string | null;
  preferred_age_min?: number | null;
  preferred_age_max?: number | null;
  event_discovery_prefs?: unknown;
  discoverable?: boolean | null;
  discovery_mode?: string | null;
  discovery_snooze_until?: string | null;
  discovery_audience?: string | null;
  activity_status_visibility?: string | null;
  distance_visibility?: string | null;
  event_attendance_visibility?: string | null;
  show_online_status?: boolean | null;
  account_paused?: boolean | null;
  account_paused_until?: string | null;
  is_paused?: boolean | null;
  paused_at?: string | null;
  paused_until?: string | null;
  pause_reason?: string | null;
  is_suspended?: boolean | null;
  suspension_reason?: string | null;
  email_unsubscribed?: boolean | null;
  community_agreed_at?: string | null;
  referred_by?: string | null;
  referrer_name?: string | null;
  events_attended?: number | null;
  total_matches?: number | null;
  total_conversations?: number | null;
};

export async function fetchMyProfileSettings(): Promise<MyProfileSettingsRow | null> {
  const { data, error } = await supabase.rpc("get_my_profile_settings");
  if (error) throw error;
  if (!data || typeof data !== "object" || Array.isArray(data)) return null;
  return data as MyProfileSettingsRow;
}
