import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import test from "node:test";

const root = process.cwd();

function read(path: string): string {
  return readFileSync(join(root, path), "utf8");
}

const copy = read("shared/chat/vibeClipCaptureCopy.ts");
const webRecorder = read("src/components/chat/VideoMessageRecorder.tsx");
const webLibraryHelper = read("src/lib/webVibeClipLibraryUpload.ts");
const webVibeClipOptions = read("src/components/chat/VibeClipSendOptionsSheet.tsx");
const webPhotoOptions = read("src/components/chat/PhotoSendOptionsDialog.tsx");
const webPhotoCamera = read("src/components/chat/PhotoCameraCaptureDialog.tsx");
const webChat = read("src/pages/Chat.tsx");
const webApp = read("src/App.tsx");
const webMessagesHook = read("src/hooks/useMessages.ts");
const webOutboxContext = read("src/contexts/WebChatOutboxContext.tsx");
const webOutboxExecute = read("src/lib/webChatOutbox/execute.ts");
const webChatMediaResolver = read("src/lib/mediaAssetResolver.ts");
const vibeClipRecovery = read("shared/chat/vibeClipRecovery.ts");
const uploadAttentionTargets = read("shared/chat/uploadAttentionTargets.ts");
const outboxReconciliation = read("shared/chat/outboxReconciliation.ts");
const webUploadMime = read("src/lib/webUploadMime.ts");
const webVibeClipBubble = read("src/components/chat/VibeClipBubble.tsx");
const webVideoBubble = read("src/components/chat/VideoMessageBubble.tsx");
const webInlinePlaybackRegistry = read("src/components/chat/inlineVideoPlaybackRegistry.ts");
const webVideoLightbox = read("src/components/chat/ChatVideoLightbox.tsx");
const webStreamUpload = read("src/services/chatVibeClipStreamUploadService.ts");
const webMediaSdkVideoUploads = read("src/lib/mediaSdk/webVideoUploads.ts");
const nativeChat = read("apps/mobile/app/chat/[id].tsx");
const nativeChatApi = read("apps/mobile/lib/chatApi.ts");
const nativeLayout = read("apps/mobile/app/_layout.tsx");
const nativePhotoOptions = read("apps/mobile/components/chat/PhotoSendOptionsSheet.tsx");
const nativePhotoCamera = read("apps/mobile/components/chat/ChatPhotoCameraModal.tsx");
const nativeVibeClipCard = read("apps/mobile/components/chat/VibeClipCard.tsx");
const nativeMediaViewer = read("apps/mobile/components/chat/ChatThreadMediaViewer.tsx");
const nativeUpload = read("apps/mobile/lib/chatMediaUpload.ts");
const nativeOutboxExecute = read("apps/mobile/lib/chatOutbox/execute.ts");
const nativeStreamUpload = read("apps/mobile/lib/chatVibeClipStreamUpload.ts");
const nativeMediaSdkVideoUploads = read("apps/mobile/lib/mediaSdk/nativeVideoUploads.ts");
const nativeMediaCache = read("apps/mobile/lib/chatOutbox/mediaCache.ts");
const nativeOutboxContext = read("apps/mobile/lib/chatOutbox/ChatOutboxContext.tsx");
const nativeOutboxRunner = read("apps/mobile/lib/chatOutbox/ChatOutboxRunner.tsx");
const nativeChatMediaResolver = read("apps/mobile/lib/mediaAssetResolver.ts");
const uploadChatVideo = read("supabase/functions/upload-chat-video/index.ts");
const uploadImage = read("supabase/functions/upload-image/index.ts");
const uploadVoice = read("supabase/functions/upload-voice/index.ts");
const uploadEventCover = read("supabase/functions/upload-event-cover/index.ts");
const sendMessage = read("supabase/functions/send-message/index.ts");
const sendGameEvent = read("supabase/functions/send-game-event/index.ts");
const createChatVibeClipUpload = read("supabase/functions/create-chat-vibe-clip-upload/index.ts");
const completeChatVibeClipUpload = read("supabase/functions/complete-chat-vibe-clip-upload/index.ts");
const syncChatVibeClipStatus = read("supabase/functions/sync-chat-vibe-clip-status/index.ts");
const dismissChatVibeClipUpload = read("supabase/functions/dismiss-chat-vibe-clip-upload/index.ts");
const chatVibeClipShared = read("supabase/functions/_shared/chat-vibe-clips.ts");
const vibeClipAnalytics = read("shared/chat/vibeClipAnalytics.ts");
const mediaTelemetry = read("shared/media/mediaTelemetry.ts");
const mediaLifecycleShared = read("supabase/functions/_shared/media-lifecycle.ts");
const getChatMediaUrl = read("supabase/functions/get-chat-media-url/index.ts");
const bunnyStreamTokens = read("supabase/functions/_shared/bunny-stream-tokens.ts");
const videoWebhook = read("supabase/functions/video-webhook/index.ts");
const chatThreadPage = read("supabase/functions/chat-thread-page/index.ts");
const chatVibeClipMigration = read("supabase/migrations/20260518120000_chat_vibe_clip_bunny_stream.sql");
const chatVibeClipRecoveryDismissalMigration = read("supabase/migrations/20260521001000_chat_vibe_clip_recovery_dismissal.sql");
const supabaseConfig = read("supabase/config.toml");

test("shared Vibe Clip upload limits stay aligned across clients", () => {
  assert.match(copy, /export const VIBE_CLIP_MAX_DURATION_SEC = 30/);
  assert.match(copy, /export const VIBE_CLIP_MAX_SOURCE_BYTES = 200 \* 1024 \* 1024/);
  assert.match(copy, /export const VIBE_CLIP_MAX_SOURCE_MB = 200/);
  assert.match(copy, /export const VIBE_CLIP_SOFT_SOURCE_BYTES = 75 \* 1024 \* 1024/);
  assert.match(copy, /VIBE_CLIP_UPLOAD_TOO_LONG/);
  assert.match(copy, /VIBE_CLIP_UPLOAD_TOO_LARGE/);
  assert.match(copy, /VIBE_CLIP_WEB_TOAST_CAMERA_SWITCH_UNAVAILABLE/);
});

test("web recorder supports saved-video upload with the same constraints", () => {
  assert.match(webRecorder, /type="file"[\s\S]{0,120}accept="video\/\*"/);
  assert.match(webRecorder, /startCamera\(facingMode, \{ cancelOnError: false \}\)/);
  assert.match(webRecorder, /disabled=\{!isRecording && \(!cameraReady \|\| isProcessingUpload\)\}/);
  assert.match(webRecorder, /prepareWebVibeClipLibraryFile/);
  assert.match(webRecorder, /const prepared = await prepareWebVibeClipLibraryFile\(file\)/);
  assert.match(webRecorder, /durationBucketFromSeconds\(prepared\.durationSeconds\)/);
  assert.match(webRecorder, /onRecordingComplete\(prepared\.file, prepared\.durationSeconds, prepared\.meta\)/);
  assert.match(webRecorder, /showLibraryUpload = true/);
});

test("web library helper validates saved-video uploads with the same constraints", () => {
  assert.match(webLibraryHelper, /export function looksLikeVideoFile/);
  assert.match(webLibraryHelper, /normalized !== null && normalized !== GENERIC_UPLOAD_MIME_TYPE/);
  assert.match(webLibraryHelper, /export function readSelectedVideoMetadata/);
  assert.match(webLibraryHelper, /video\.onloadedmetadata = null/);
  assert.match(webLibraryHelper, /URL\.revokeObjectURL\(objectUrl\)/);
  assert.match(webLibraryHelper, /file\.size <= 0/);
  assert.match(webLibraryHelper, /file\.size > VIBE_CLIP_MAX_SOURCE_BYTES/);
  assert.match(webLibraryHelper, /metadata\.durationSeconds > VIBE_CLIP_MAX_DURATION_SEC \+ 0\.25/);
  assert.match(webLibraryHelper, /captureSource: "library"/);
  assert.match(webLibraryHelper, /videoMimeTypeForUpload\(file\.type, file\.name\) \?\? undefined/);
  assert.match(webLibraryHelper, /fileName: file\.name \|\| undefined/);
  assert.match(webLibraryHelper, /aspectRatio: metadata\.aspectRatio/);
});

test("web chat routes media buttons through polished pickers without changing send paths", () => {
  assert.match(webChat, /VibeClipSendOptionsSheet = lazy/);
  assert.match(webChat, /PhotoSendOptionsDialog = lazy/);
  assert.match(webChat, /PhotoCameraCaptureDialog = lazy/);
  assert.match(webChat, /const \[showPhotoOptions, setShowPhotoOptions\] = useState\(false\)/);
  assert.match(webChat, /const \[showPhotoCamera, setShowPhotoCamera\] = useState\(false\)/);
  assert.match(webChat, /const \[showVibeClipOptions, setShowVibeClipOptions\] = useState\(false\)/);
  assert.match(webChat, /setShowPhotoOptions\(true\)/);
  assert.match(webChat, /setShowPhotoCamera\(true\)/);
  assert.match(webChat, /setShowVibeClipOptions\(true\)/);
  assert.doesNotMatch(webChat, /photoCameraInputRef/);
  assert.doesNotMatch(webChat, /capture="environment"/);
  assert.match(webChat, /onTakePhoto=\{openPhotoCamera\}/);
  assert.match(webChat, /onChooseLibrary=\{triggerPhotoFilePicker\}/);
  assert.match(webChat, /onCapturePhoto=\{queuePhotoFile\}/);
  assert.match(webChat, /onLibraryClipReady=\{handleVibeClipLibraryReady\}/);
  assert.match(webChat, /showLibraryUpload=\{false\}/);
});

test("web Vibe Clip options sheet owns library validation and preserves recorder path", () => {
  assert.match(webVibeClipOptions, /type="file"[\s\S]{0,120}accept="video\/\*"/);
  assert.match(webVibeClipOptions, /prepareWebVibeClipLibraryFile/);
  assert.match(webVibeClipOptions, /const prepared = await prepareWebVibeClipLibraryFile\(file\)/);
  assert.match(webVibeClipOptions, /trackVibeClipEvent\("clip_record_started"/);
  assert.match(webVibeClipOptions, /trackVibeClipEvent\("clip_record_completed"/);
  assert.match(webVibeClipOptions, /durationBucketFromSeconds\(prepared\.durationSeconds\)/);
  assert.match(webVibeClipOptions, /await onLibraryClipReady\(prepared\.file, prepared\.durationSeconds, prepared\.meta\)/);
  assert.match(webVibeClipOptions, /onRecord\(\)/);
  assert.match(webVibeClipOptions, /VIBE_CLIP_SHEET_TITLE/);
  assert.match(webVibeClipOptions, /VIBE_CLIP_LIBRARY_HINT/);
});

test("web photo options dialog keeps action routing in the caller", () => {
  assert.match(webPhotoOptions, /Send a photo/);
  assert.match(webPhotoOptions, /Choose how you'd like to add your picture\./);
  assert.match(webPhotoOptions, /onTakePhoto\(\)/);
  assert.match(webPhotoOptions, /onChooseLibrary\(\)/);
  assert.doesNotMatch(webPhotoOptions, /capture=/);
});

test("web take-photo path opens in-app camera capture instead of upload picker", () => {
  assert.match(webPhotoCamera, /SwitchCamera/);
  assert.match(webPhotoCamera, /type PhotoCameraFacingMode = "user" \| "environment"/);
  assert.match(webPhotoCamera, /const \[facingMode, setFacingMode\] = useState<PhotoCameraFacingMode>\("environment"\)/);
  assert.match(webPhotoCamera, /navigator\.mediaDevices\.enumerateDevices/);
  assert.match(webPhotoCamera, /setHasMultipleCameras\(devices\.filter\(\(device\) => device\.kind === "videoinput"\)\.length > 1\)/);
  assert.match(webPhotoCamera, /navigator\.mediaDevices\?\.getUserMedia/);
  assert.match(webPhotoCamera, /onChooseLibrary\?: \(\) => void/);
  assert.match(webPhotoCamera, /Choose from library/);
  assert.match(webPhotoCamera, /startCamera\("environment"\)/);
  assert.match(webPhotoCamera, /exactFacingMode\?: boolean/);
  assert.match(webPhotoCamera, /facingMode:\s*opts\?\.exactFacingMode \? \{ exact: facingMode \} : \{ ideal: facingMode \}/);
  assert.match(webPhotoCamera, /function shouldRetryWithGenericCamera/);
  assert.match(webPhotoCamera, /name !== "NotAllowedError" && name !== "SecurityError"/);
  assert.match(webPhotoCamera, /function facingModeFromStream\(stream: MediaStream, fallback: PhotoCameraFacingMode\)/);
  assert.match(webPhotoCamera, /stream\.getVideoTracks\(\)\[0\]\?\.getSettings\?\.\(\)\.facingMode/);
  assert.match(webPhotoCamera, /setFacingMode\(facingModeFromStream\(stream, nextFacingMode\)\)/);
  assert.match(webPhotoCamera, /getUserMedia\(\{\s*audio: false,\s*video: true/);
  assert.match(webPhotoCamera, /preserveExistingStream/);
  assert.match(webPhotoCamera, /previousStream\.getTracks\(\)\.forEach\(\(track\) => track\.stop\(\)\)/);
  assert.match(webPhotoCamera, /const nextFacingMode = facingMode === "user" \? "environment" : "user"/);
  assert.match(webPhotoCamera, /exactFacingMode: !!opts\?\.preserveExistingStream/);
  assert.match(webPhotoCamera, /startCamera\(nextFacingMode, \{ preserveExistingStream: true, silentError: true \}\)/);
  assert.match(webPhotoCamera, /streamRef\.current\?\.getTracks\(\)\.forEach\(\(track\) => track\.stop\(\)\)/);
  assert.match(webPhotoCamera, /canvas\.toBlob/);
  assert.match(webPhotoCamera, /function dataUrlToBlob/);
  assert.match(webPhotoCamera, /canvas\.toDataURL\(CAPTURE_FILE_TYPE, CAPTURE_QUALITY\)/);
  assert.match(webPhotoCamera, /context\.scale\(-1, 1\)/);
  assert.match(webPhotoCamera, /facingMode === "user" && "scale-x-\[-1\]"/);
  assert.match(webPhotoCamera, /new File\(\[blob\], `chat-photo-\$\{Date\.now\(\)\}\.jpg`, \{ type: CAPTURE_FILE_TYPE \}\)/);
  assert.match(webPhotoCamera, /const CAPTURE_FILE_TYPE = "image\/jpeg"/);
  assert.match(webPhotoCamera, /const CAPTURE_QUALITY = 0\.85/);
  assert.match(webPhotoCamera, /const captureLockRef = useRef\(false\)/);
  assert.match(webPhotoCamera, /const submitLockRef = useRef\(false\)/);
  assert.match(webPhotoCamera, /submitLockRef\.current/);
  assert.match(
    webPhotoCamera,
    /const sent = await onCapturePhoto\(capturedFile\);[\s\S]{0,240}if \(sent\) \{[\s\S]{0,160}onOpenChange\(false\);[\s\S]{0,160}return;[\s\S]{0,240}setErrorMessage\("Could not send the photo\. Please try again\."\)/,
  );
});

test("native chat photo flow uses a dedicated sheet and in-app switchable camera", () => {
  assert.match(nativeChat, /PhotoSendOptionsSheet/);
  assert.match(nativeChat, /ChatPhotoCameraModal/);
  assert.match(nativeChat, /const \[showPhotoOptionsSheet, setShowPhotoOptionsSheet\] = useState\(false\)/);
  assert.match(nativeChat, /const \[showPhotoCameraModal, setShowPhotoCameraModal\] = useState\(false\)/);
  assert.match(nativeChat, /const uploadPhotoUriAndSend = async \(uri: string, mimeType\?: string \| null\): Promise<boolean>/);
  assert.match(nativeChat, /setShowPhotoOptionsSheet\(true\)/);
  assert.match(nativeChat, /runAfterPhotoSheetDismiss/);
  assert.match(nativeChat, /useCameraPermissions/);
  assert.match(nativeChat, /const \[, requestPhotoCameraPermission\] = useCameraPermissions\(\)/);
  assert.match(nativeChat, /const openPhotoCameraModal = async \(\) => \{[\s\S]+requestPhotoCameraPermission\(\)[\s\S]+setShowPhotoCameraModal\(true\)/);
  assert.doesNotMatch(nativeChat, /const openPhotoCameraModal = async \(\) => \{[\s\S]{0,700}ImagePicker\.requestCameraPermissionsAsync/);
  assert.match(nativeChat, /setShowPhotoCameraModal\(true\)/);
  assert.match(nativeChat, /onSendPhoto=\{uploadPhotoUriAndSend\}/);
  assert.doesNotMatch(nativeChat, /title:\s*'Send a photo'/);
  assert.doesNotMatch(nativeChat, /primaryAction:\s*\{\s*label:\s*'Take photo'/);
  assert.doesNotMatch(nativeChat, /launchCameraAsync\(\{\s*quality:\s*0\.85\s*\}\)/);

  assert.match(nativePhotoOptions, /KeyboardAwareBottomSheetModal/);
  assert.match(nativePhotoOptions, /Take Photo/);
  assert.match(nativePhotoOptions, /Choose from library/);
  assert.match(nativePhotoOptions, /onTakePhoto\(\)/);
  assert.match(nativePhotoOptions, /onChooseLibrary\(\)/);

  assert.match(nativePhotoCamera, /CameraView/);
  assert.match(nativePhotoCamera, /type CameraType/);
  assert.match(nativePhotoCamera, /const \[facing, setFacing\] = useState<CameraType>\('back'\)/);
  assert.match(nativePhotoCamera, /const cameraSessionIdRef = useRef\(0\)/);
  assert.match(nativePhotoCamera, /const \[cameraSessionId, setCameraSessionId\] = useState\(0\)/);
  assert.match(nativePhotoCamera, /const cameraViewKey = `\$\{facing\}:\$\{cameraSessionId\}`/);
  assert.match(nativePhotoCamera, /activeCameraKeyRef\.current = nextCameraKey/);
  assert.match(nativePhotoCamera, /setCameraSessionId\(nextSessionId\)/);
  assert.match(nativePhotoCamera, /activeCameraKeyRef\.current !== readyCameraKey/);
  assert.match(nativePhotoCamera, /activeCameraKeyRef\.current !== failedCameraKey/);
  assert.match(nativePhotoCamera, /key=\{cameraViewKey\}/);
  assert.match(nativePhotoCamera, /onCameraReady=\{\(\) => handleCameraReady\(cameraViewKey\)\}/);
  assert.doesNotMatch(nativePhotoCamera, /CAMERA_READY_FALLBACK_MS|setTimeout/);
  assert.match(nativePhotoCamera, /takePictureAsync\(\{/);
  assert.match(nativePhotoCamera, /quality: 0\.85/);
  assert.match(nativePhotoCamera, /const nextFacing = facingRef\.current === 'front' \? 'back' : 'front'/);
  assert.match(nativePhotoCamera, /prepareCameraForFacing\(nextFacing\)/);
  assert.match(nativePhotoCamera, /name="camera-reverse-outline"/);
  assert.match(nativePhotoCamera, /accessibilityLabel="Switch camera"/);
  assert.match(nativePhotoCamera, /onSendPhoto\(capturedUri, CAPTURE_MIME_TYPE\)/);
});

test("web recorder exposes safe camera flip on eligible devices", () => {
  assert.match(webRecorder, /navigator\.mediaDevices\.enumerateDevices/);
  assert.match(webRecorder, /setHasMultipleCameras\(videoInputs\.length > 1\)/);
  assert.match(webRecorder, /<SwitchCamera/);
  assert.match(webRecorder, /hasMultipleCameras && !isRecording/);
  assert.match(webRecorder, /startCamera\(newFacing, \{ cancelOnError: false, silentError: true \}\)/);
  assert.match(webRecorder, /VIBE_CLIP_WEB_TOAST_CAMERA_SWITCH_UNAVAILABLE/);
  assert.match(
    webRecorder,
    /const previousStream = streamRef\.current[\s\S]+getUserMedia[\s\S]+previousStream\?\.getTracks\(\)\.forEach/,
  );
});

test("web queue and upload preserve validated library video metadata", () => {
  assert.match(webChat, /Math\.min\(\s*VIBE_CLIP_MAX_DURATION_SEC/);
  assert.match(webChat, /measuredDurationSeconds > VIBE_CLIP_MAX_DURATION_SEC \+ 0\.25/);
  assert.match(webChat, /toast\.error\(VIBE_CLIP_UPLOAD_TOO_LONG\(\)\)/);
  assert.match(webChat, /const captureSource = meta\?\.captureSource \?\? "web_recorder"/);
  assert.match(webChat, /const videoMimeType =[\s\S]{0,160}videoMimeTypeForUpload\(meta\?\.mimeType \|\| videoBlob\.type, storedVideoName\) \?\? GENERIC_UPLOAD_MIME_TYPE/);
  assert.match(webChat, /mimeType: videoMimeType/);
  assert.match(webChat, /fileName: storedVideoName/);
  assert.doesNotMatch(webChat, /videoBlob\.type \|\| "video\/mp4"/);
  assert.match(webChat, /aspectRatio: meta\?\.aspectRatio \?\? null/);
  assert.match(webChat, /captions: meta\?\.captions \?\? null/);
  assert.match(webChat, /videoBlob\.size > VIBE_CLIP_MAX_SOURCE_BYTES/);
  assert.match(webChat, /videoBlob\.size > VIBE_CLIP_SOFT_SOURCE_BYTES/);
  assert.match(webChat, /videoMimeType === GENERIC_UPLOAD_MIME_TYPE/);
  assert.match(webChat, /VIBE_CLIP_UPLOAD_INVALID_TYPE/);
  assert.match(webOutboxExecute, /videoMimeTypeForUpload\(blob\.type, storedName\)/);
  assert.match(webOutboxExecute, /videoMimeTypeForUpload\(payload\.mimeType, storedName\)/);
  assert.match(webOutboxExecute, /uploadFileNameForMimeType\("video", "chat-vibe-clip", mimeType, storedName\)/);
  assert.match(webOutboxExecute, /uploadAndPublishChatVibeClipToBunnyStream/);
  assert.match(webOutboxExecute, /completePublishedChatVibeClipUpload/);
  assert.match(webOutboxExecute, /captions: payload\.captions \?\? null/);
  assert.match(webOutboxExecute, /ChatVibeClipUploadedButUnpublishedError/);
  assert.match(webOutboxExecute, /isBunnyStreamPlaybackRef\(item\.uploadedMediaUrl\)/);
  assert.match(webOutboxExecute, /bunnyStreamVideoIdFromRef\(trimmed\)/);
  assert.doesNotMatch(webOutboxExecute, /invokePublishVibeClip/);
  assert.doesNotMatch(webMessagesHook, /usePublishVibeClip/);
  assert.doesNotMatch(webMessagesHook, /publish-vibe-clip/);
  assert.match(webStreamUpload, /new tus\.Upload\(params\.file/);
  assert.match(webStreamUpload, /chunkSize: TUS_CHUNK_SIZE/);
  assert.match(webStreamUpload, /upload\.findPreviousUploads\(\)/);
  assert.match(webStreamUpload, /class ChatVibeClipUploadedButUnpublishedError/);
  assert.match(webStreamUpload, /completePublishedChatVibeClipUpload/);
  assert.match(webStreamUpload, /bunnyStreamVideoIdFromRef\(params\.playbackRef\)/);
  assert.match(webStreamUpload, /created\.status === "failed"/);
  assert.match(webStreamUpload, /!created\.status \|\| created\.status === "uploading"/);
  assert.match(webStreamUpload, /create-chat-vibe-clip-upload/);
  assert.match(webStreamUpload, /complete-chat-vibe-clip-upload/);
  assert.match(webStreamUpload, /params\.file\.size > VIBE_CLIP_MAX_SOURCE_BYTES/);
  assert.doesNotMatch(webStreamUpload, /params\.file\.type \|\| "video\/mp4"/);
  assert.doesNotMatch(webStreamUpload, /created\.mime_type \|\| params\.file\.type \|\| "video\/mp4"/);
  assert.equal(existsSync(join(root, "src/services/chatVideoUploadService.ts")), false);
  assert.match(webUploadMime, /"video\/mov": "video\/quicktime"/);
  assert.match(webUploadMime, /"video\/m4v": "video\/x-m4v"/);
});

test("Chat Vibe Clip media v2 cutover is upload-start gated inside the platform facade", () => {
  assert.doesNotMatch(webOutboxContext, /useFeatureFlag\("media_v2_video"\)/);
  assert.doesNotMatch(webOutboxContext, /mediaV2VideoEnabled: mediaV2Video\.enabled/);
  assert.doesNotMatch(webOutboxExecute, /options: \{ mediaV2VideoEnabled\?: boolean; mediaV2PhotoEnabled\?: boolean; mediaV2VoiceEnabled\?: boolean \} = \{\}/);
  assert.match(webOutboxExecute, /uploadAndPublishChatVibeClipWithMediaSdk/);
  assert.doesNotMatch(webOutboxExecute, /options\.mediaV2VideoEnabled/);
  assert.match(webOutboxExecute, /isBunnyStreamPlaybackRef\(item\.uploadedMediaUrl\)[\s\S]{0,160}completePublishedChatVibeClipUpload/);
  assert.match(webOutboxExecute, /options: \{ signal\?: AbortSignal \| null \} = \{\}/);
  assert.match(webOutboxExecute, /signal: options\.signal \?\? null/);
  assert.match(webOutboxContext, /processingAbortControllersRef/);
  assert.match(webOutboxContext, /processingAbortControllersRef\.current\.get\(itemId\)\?\.abort\(\)/);
  assert.match(webOutboxContext, /processingAbortControllersRef\.current\.set\(next\.id, abortController\)/);
  assert.match(webOutboxContext, /\{ signal: abortController\.signal \}/);

  assert.doesNotMatch(nativeOutboxContext, /useFeatureFlag\('media_v2_video'\)/);
  assert.doesNotMatch(nativeOutboxContext, /mediaV2VideoEnabled: mediaV2Video\.enabled/);
  assert.doesNotMatch(nativeOutboxExecute, /options: \{ mediaV2VideoEnabled\?: boolean; mediaV2PhotoEnabled\?: boolean; mediaV2VoiceEnabled\?: boolean \} = \{\}/);
  assert.match(nativeOutboxExecute, /uploadAndPublishChatVibeClipWithMediaSdk/);
  assert.doesNotMatch(nativeOutboxExecute, /options\.mediaV2VideoEnabled/);
  assert.match(nativeOutboxExecute, /isBunnyStreamPlaybackRef\(item\.uploadedMediaUrl\)[\s\S]{0,160}completePublishedChatVibeClipUpload/);
  assert.match(nativeOutboxExecute, /options: \{ signal\?: AbortSignal \| null \} = \{\}/);
  assert.match(nativeOutboxExecute, /signal: options\.signal \?\? null/);
  assert.match(nativeOutboxContext, /processingAbortControllersRef/);
  assert.match(nativeOutboxContext, /processingAbortControllersRef\.current\.get\(itemId\)\?\.abort\(\)/);
  assert.match(nativeOutboxContext, /processingAbortControllersRef\.current\.set\(next\.id, abortController\)/);
  assert.match(nativeOutboxContext, /\{ signal: abortController\.signal \}/);

  assert.match(webMediaSdkVideoUploads, /evaluateClientFeatureFlagForUpload\("media_v2_video"\)/);
  assert.match(webMediaSdkVideoUploads, /MEDIA_UPLOAD_PATH_EVENT_NAMES/);
  assert.match(webMediaSdkVideoUploads, /createMediaUploadPathTelemetryFields/);
  assert.match(webMediaSdkVideoUploads, /uploadChatVibeClip: uploadWebChatVibeClipViaLegacyService/);
  assert.match(webMediaSdkVideoUploads, /return uploadAndPublishChatVibeClipToBunnyStream\(\{ \.\.\.params, clientRequestId \}\)/);
  assert.match(webMediaSdkVideoUploads, /signal: \(input\.options\?\.signal as AbortSignal \| null \| undefined\) \?\? undefined/);
  assert.match(webMediaSdkVideoUploads, /signal: params\.signal \?\? null/);
  assert.match(webMediaSdkVideoUploads, /chatClipResultsByClientRequestId/);
  assert.match(webMediaSdkVideoUploads, /chatClipErrorsByClientRequestId/);
  assert.match(webMediaSdkVideoUploads, /scheduleChatClipTransientStateCleanup/);
  assert.match(nativeMediaSdkVideoUploads, /evaluateClientFeatureFlagForUpload\('media_v2_video'\)/);
  assert.match(nativeMediaSdkVideoUploads, /MEDIA_UPLOAD_PATH_EVENT_NAMES/);
  assert.match(nativeMediaSdkVideoUploads, /createMediaUploadPathTelemetryFields/);
  assert.match(nativeMediaSdkVideoUploads, /signal: \(input\.options\?\.signal as AbortSignal \| null \| undefined\) \?\? undefined/);
  assert.match(nativeMediaSdkVideoUploads, /signal: params\.signal \?\? null/);
  assert.match(webStreamUpload, /signal\?: AbortSignal \| null/);
  assert.match(webStreamUpload, /upload\.abort\(\)/);
  assert.match(webStreamUpload, /addEventListener\("abort", onAbort/);
  assert.match(webStreamUpload, /removeEventListener\("abort", onAbort/);
  assert.match(nativeStreamUpload, /signal\?: AbortSignal \| null/);
  assert.match(nativeStreamUpload, /upload\.abort\(\)/);
  assert.match(nativeStreamUpload, /addEventListener\('abort', onAbort/);
  assert.match(nativeStreamUpload, /removeEventListener\('abort', onAbort/);
  assert.match(webMediaSdkVideoUploads, /chatClipProgressByClientRequestId/);
  assert.match(webMediaSdkVideoUploads, /CHAT_CLIP_TRANSIENT_STATE_TTL_MS = 60 \* 60 \* 1000/);
  assert.match(webMediaSdkVideoUploads, /function fileFromWebVideoSource\(source: File \| Blob\): File/);
  assert.match(webMediaSdkVideoUploads, /web_media_file_constructor_missing/);
  assert.doesNotMatch(webMediaSdkVideoUploads, /: new File\(\[input\.source\]/);
  assert.match(webMediaSdkVideoUploads, /controls\.dispatch\(\{[\s\S]{0,80}type: "ready"/);
  assert.match(webMediaSdkVideoUploads, /onProgress\?\.\(fraction\);[\s\S]{0,80}scheduleChatClipTransientStateCleanup\(clientRequestId\)/);
  assert.match(webMediaSdkVideoUploads, /waitForMediaUploadTaskTerminal/);

  assert.match(nativeMediaSdkVideoUploads, /uploadChatVibeClip: uploadNativeChatVibeClipViaLegacyService/);
  assert.match(nativeMediaSdkVideoUploads, /uploadAndPublishChatVibeClipToBunnyStream\(\{/);
  assert.match(nativeMediaSdkVideoUploads, /chatClipResultsByClientRequestId/);
  assert.match(nativeMediaSdkVideoUploads, /chatClipErrorsByClientRequestId/);
  assert.match(nativeMediaSdkVideoUploads, /chatClipProgressByClientRequestId/);
  assert.match(nativeMediaSdkVideoUploads, /CHAT_CLIP_TRANSIENT_STATE_TTL_MS = 60 \* 60 \* 1000/);
  assert.match(nativeMediaSdkVideoUploads, /scheduleChatClipTransientStateCleanup/);
  assert.match(nativeMediaSdkVideoUploads, /mimeFromExtension\(extensionFromFileUri\(params\.uri\)\)/);
  assert.match(nativeMediaSdkVideoUploads, /controls\.dispatch\(\{[\s\S]{0,80}type: 'ready'/);
  assert.match(nativeMediaSdkVideoUploads, /onProgress\?\.\(fraction\);[\s\S]{0,80}scheduleChatClipTransientStateCleanup\(clientRequestId\)/);
  assert.match(nativeMediaSdkVideoUploads, /waitForMediaUploadTaskTerminal/);
});

test("web chat image outbox no longer invents JPEG declarations", () => {
  assert.match(webChat, /const imageMimeType = imageMimeTypeForUpload\(file\.type, file\.name\)/);
  assert.match(webChat, /payload: \{ kind: "image", blobKey, mimeType: imageMimeType, fileName: file\.name \|\| undefined \}/);
  assert.doesNotMatch(webChat, /file\.type \|\| "image\/jpeg"/);
  assert.match(webOutboxExecute, /imageMimeTypeForUpload\(blob\.type, storedName\)/);
  assert.match(webOutboxExecute, /imageMimeTypeForUpload\(payload\.mimeType, storedName\)/);
  assert.match(webOutboxExecute, /uploadFileNameForMimeType\("image", "chat", mimeType, storedName\)/);
  assert.doesNotMatch(webOutboxExecute, /"chat\.jpg", \{ type: payload\.mimeType \|\| blob\.type \|\| "image\/jpeg" \}/);
});

test("video bubbles remain adaptive and full-width across web and native chat", () => {
  assert.match(webVibeClipBubble, /w-\[min\(17\.5rem,calc\(100svw-4rem\)\)\] max-w-full/);
  assert.doesNotMatch(webVibeClipBubble, /100vw|w-screen/);
  assert.match(webVibeClipBubble, /Math\.max\(0\.5, Math\.min\(1\.2, displayMeta\.aspectRatio\)\)/);
  assert.match(webVibeClipBubble, /<AspectRatio ratio=\{clipAspectRatio\}>/);
  assert.match(webVibeClipBubble, /w-full h-full object-cover bg-black/);
  assert.match(webVibeClipBubble, /syncChatVibeClipUploadStatus/);
  assert.match(webVibeClipBubble, /const shouldAutoSyncProcessingStatus =/);
  assert.match(webVibeClipBubble, /const effectiveClientRequestId = clientRequestId \?\? meta\.clientRequestId \?\? null/);
  assert.match(webVibeClipBubble, /clientRequestId: effectiveClientRequestId/);
  assert.match(webVibeClipBubble, /CHAT_VIBE_CLIP_STATUS_SYNC_SAFETY_NET_INTERVAL_MS = 30_000/);
  assert.doesNotMatch(webVibeClipBubble, /CHAT_VIBE_CLIP_STATUS_SYNC_DELAY_MS/);
  assert.doesNotMatch(webVibeClipBubble, /CHAT_VIBE_CLIP_STATUS_SYNC_FAST_INTERVAL_MS/);
  assert.match(webVibeClipBubble, /statusSyncInFlightRef/);
  assert.match(webVibeClipBubble, /statusSyncRunIdRef/);
  assert.match(webVibeClipBubble, /isMountedRef\.current = true/);
  assert.match(webVibeClipBubble, /if \(statusSyncInFlightRef\.current\) return/);
  assert.match(webVibeClipBubble, /data-testid="vibe-clip-recovery-panel"/);
  assert.match(webVibeClipBubble, /data-testid="vibe-clip-resume-upload"/);
  assert.match(webVibeClipBubble, /data-testid="vibe-clip-discard-send-again"/);
  assert.match(webVibeClipBubble, /data-testid="vibe-clip-check-status"/);
  assert.match(vibeClipRecovery, /export function buildVibeClipRecovery/);
  assert.match(vibeClipRecovery, /\? "reissue_credentials"/);
  assert.match(webChat, /buildVibeClipRecovery/);
  assert.match(webChat, /vibeClipRecoveryFromDecision/);
  assert.doesNotMatch(webChat, /function vibeClipRecoveryForOutboxItem/);
  assert.match(webChat, /const webOutboxItemsForMatch = webOutbox\.itemsForMatch/);
  assert.match(webChat, /const outboxMatchItems = useMemo\(/);
  assert.match(webChat, /trackVibeClipEvent\("clip_recovery_status"/);
  assert.match(webChat, /outcome: decision\.telemetryOutcome/);
  assert.match(webChat, /try \{[\s\S]{0,120}getOutboxBlob\(item\.payload\.blobKey\)[\s\S]{0,160}catch \{[\s\S]{0,80}next\[item\.id\] = false/);
  assert.match(webChat, /webOutbox\.retryVibeClipUpload\(groupedMessage\.outboxItemId!, strategy\)/);
  assert.match(webChat, /webOutbox\.remove\(groupedMessage\.outboxItemId\);[\s\S]{0,500}openVibeClipOptions\(\)/);
  assert.match(webVibeClipBubble, /isAwaitingPlaybackIntent/);
  assert.match(webVibeClipBubble, /const isLocalPreview = isLocalPreviewUrl\(displayMeta\.videoUrl\)/);
  assert.match(webVibeClipBubble, /!isAwaitingPlaybackIntent && !isLocalPreview/);
  assert.match(webVibeClipBubble, /isReady \|\| isLocalPreview \? "opacity-100" : "opacity-0"/);
  assert.match(webVibeClipBubble, /role=\{isSurfaceInteractive \? "button" : undefined\}/);
  assert.match(webVibeClipBubble, /type VibeClipMediaRefreshReason = "preview" \| "initial" \| "playback" \| "manual"/);
  assert.match(webVibeClipBubble, /if \(reason === "preview"\) return refreshPoster\(\)/);
  assert.match(webVibeClipBubble, /poster=\{showPosterVisual \? displayableThumbnailUrl \?\? undefined : undefined\}/);
  assert.match(webVibeClipBubble, /shouldResolvePosterPreview/);
  assert.match(webVibeClipBubble, /posterRetryStateRef/);
  assert.match(webVibeClipBubble, /fallbackUrls: thumbnailFallbackUrls/);
  assert.match(webVibeClipBubble, /const handlePosterImageError = useCallback/);
  assert.match(webVibeClipBubble, /!showPreparingOverlay[\s\S]{0,80}!hasStartedPlayback/);
  assert.doesNotMatch(webVibeClipBubble, /const posterNotReady =\s*!isReady/);
  assert.match(webVibeClipBubble, /POSTER_PREVIEW_RETRY_DELAYS_MS = \[1000, 3000, 8000\]/);
  assert.match(webVibeClipBubble, /playableVideoUrlRef/);
  assert.match(webVibeClipBubble, /playableThumbnailUrlRef/);
  assert.match(webVibeClipBubble, /requestImmersiveWithCurrentMedia/);
  assert.match(webChat, /const handleRequestClipImmersive = useCallback/);
  assert.match(webChat, /url: media\?\.videoUrl \?\? displayClipVideoUrl/);
  assert.match(webChat, /onRequestImmersive=\{handleRequestClipImmersive\}/);
  assert.match(webVibeClipBubble, /void refreshClipMedia\("preview"\)\.finally\(/);
  assert.match(webVibeClipBubble, /MAX_CLIP_PLAYBACK_REFRESH_ATTEMPTS = 2/);
  assert.match(webVibeClipBubble, /PLAYBACK_REFRESH_RETRY_DELAY_MS = 650/);
  assert.match(webVibeClipBubble, /getCachedMediaAssetFailureCode/);
  assert.match(webVibeClipBubble, /isTransientMediaAssetFailureCode/);
  assert.match(webVibeClipBubble, /setPosterImageBroken\(true\)/);
  assert.match(webVibeClipBubble, /handlePosterImageError\(\)/);
  assert.match(webVibeClipBubble, /if \(displayableFreshThumbnailUrl\) \{[\s\S]{0,220}setPosterImageBroken\(false\)/);
  assert.doesNotMatch(webVibeClipBubble, /if \(didRefresh\) posterRefreshAttemptedForRef\.current = null/);
  assert.match(webInlinePlaybackRegistry, /registryPauseMarks/);
  assert.match(webInlinePlaybackRegistry, /consumeInlineVideoPlaybackRegistryPause/);
  assert.match(webVibeClipBubble, /consumeInlineVideoPlaybackRegistryPause\(video\)/);
  assert.match(webVideoBubble, /consumeInlineVideoPlaybackRegistryPause\(video\)/);
  assert.match(webVibeClipBubble, /CLIP_PLAYBACK_LOAD_TIMEOUT_MS/);
  assert.match(webVibeClipBubble, /playbackRefreshAttemptCountRef\.current = 0;[\s\S]{0,160}setLoadError\(false\)/);
  assert.match(webVibeClipBubble, /aria-label=\{isMuted \? "Unmute clip" : "Mute clip"\}/);
  assert.match(webVibeClipBubble, /aria-label="Open clip full screen"/);
  assert.match(webVibeClipBubble, /video\.pause\(\);[\s\S]{0,80}setPlayRequested\(false\)/);
  assert.match(webOutboxContext, /function recoverInterruptedSendingItems/);
  assert.match(webOutboxContext, /activeProcessingIds: processingRef\.current/);
  assert.match(webOutboxContext, /force: true/);
  assert.match(webChatMediaResolver, /export async function syncChatVibeClipUploadStatus/);
  assert.match(webChatMediaResolver, /uploadId: string \| null/);
  assert.match(webChatMediaResolver, /providerReachable: boolean/);
  assert.match(webChatMediaResolver, /providerError: string \| null/);
  assert.match(webChatMediaResolver, /clientRequestId\?: string \| null/);
  assert.match(webChatMediaResolver, /if \(isUuid\(clientRequestId\)\) body\.client_request_id = clientRequestId/);
  assert.match(webChatMediaResolver, /messageId: typeof payload\?\.message_id === "string"/);
  assert.match(webOutboxContext, /syncChatVibeClipUploadStatus/);
  assert.match(webOutboxContext, /runVibeClipRecoverySweep/);
  assert.match(webOutboxContext, /void sweep\("mount_sweep"\)/);
  assert.match(webOutboxContext, /void sweep\("foreground"\)/);
  assert.match(webOutboxContext, /staleVibeClipUploadsForMatch/);
  assert.match(webOutboxContext, /staleVibeClipUploads,/);
  assert.match(uploadAttentionTargets, /export function buildRecoveryAttentionTargets/);
  assert.match(uploadAttentionTargets, /export function selectPrimaryRecoveryAttentionTarget/);
  assert.match(uploadAttentionTargets, /export function uploadAttentionTargetIdentity/);
  assert.match(uploadAttentionTargets, /export function normalizeServerRecoveryAttentionTarget/);
  assert.match(uploadAttentionTargets, /attentionId: `local:\$\{clientRequestId\}`/);
  assert.match(uploadAttentionTargets, /attentionId: `server:\$\{uploadId\}`/);
  assert.match(outboxReconciliation, /completedClientRequestIds: ReadonlySet<string>/);
  assert.match(outboxReconciliation, /serverMessageIds: ReadonlySet<string>/);
  assert.match(outboxReconciliation, /shouldPruneOutboxItemAfterServerReconcile/);
  assert.match(outboxReconciliation, /isRawMessageDisplayReadyForOutboxCompletion/);
  assert.match(outboxReconciliation, /completedByClientRequestId = input\.completedClientRequestIds\.has\(item\.id\)/);
  assert.match(outboxReconciliation, /item\.payload\?\.kind === "image" && !completedByClientRequestId/);
  assert.match(webOutboxContext, /recoveryAttentionCount/);
  assert.match(webOutboxContext, /recoveryAttentionTargets/);
  assert.match(webOutboxContext, /buildRecoveryAttentionTargets\(items, staleVibeClipUploads\)/);
  assert.match(webOutboxContext, /recoveryAttentionTargets\.length/);
  assert.match(webOutboxContext, /validateRecoveryAttentionTarget/);
  assert.match(webOutboxContext, /skipRecoveryAttentionTarget/);
  assert.match(webOutboxContext, /normalizeServerRecoveryAttentionTarget\(target, upload\)/);
  assert.match(webOutboxContext, /reconcileWithServerMessages/);
  assert.match(webOutboxContext, /shouldPruneOutboxItemAfterServerReconcile/);
  assert.match(webOutboxContext, /dismissStaleVibeClipUpload/);
  assert.match(webOutboxContext, /dismiss-chat-vibe-clip-upload/);
  assert.match(webOutboxContext, /type VibeClipRecoveryDismissResult/);
  assert.match(webOutboxContext, /response\?\.success === true/);
  assert.match(webOutboxContext, /response\.already_published \? "already_published" : "dismissed"/);
  assert.match(webOutboxContext, /attachOtherUserIdsToStaleUploads/);
  assert.match(webApp, /WebUploadRecoveryNotifier/);
  assert.match(webApp, /recoveryAttentionTargets/);
  assert.match(webApp, /uploadAttentionTargetValidationKey/);
  assert.match(webApp, /target\.status/);
  assert.match(webApp, /target\.updatedAtMs/);
  assert.match(webApp, /selectPrimaryRecoveryAttentionTarget\(visibleRecoveryAttentionTargets, currentOtherUserId\)/);
  assert.match(webApp, /currentOtherUserId === null/);
  assert.match(webApp, /try \{[\s\S]{0,120}result = await validateRecoveryAttentionTarget\(target\)/);
  assert.match(webApp, /validateRecoveryAttentionTarget\(primaryTarget\)/);
  assert.match(webApp, /skipRecoveryAttentionTarget\(primaryTarget\)/);
  assert.match(webApp, /setHiddenAttentionTarget/);
  assert.doesNotMatch(webApp, /setHiddenAttentionKey/);
  assert.match(webApp, /uploadAttention: target\.attentionId/);
  assert.match(webApp, /uploadAttentionClientRequestId: target\.clientRequestId/);
  assert.match(webApp, /uploadAttentionNonce: String\(Date\.now\(\)\)/);
  assert.match(webApp, />\s*Skip\s*</);
  assert.match(webApp, /Review recovery options in chat/);
  assert.doesNotMatch(webApp, /WEB_UPLOAD_ATTENTION_TOAST_SEEN_PREFIX/);
  assert.doesNotMatch(webApp, /hasSeenWebUploadAttentionToast/);
  assert.doesNotMatch(webApp, /media-upload-recovery-attention/);
  assert.match(webApp, /Uploads resume when you return/);
  assert.match(webChat, /useSearchParams/);
  assert.match(webChat, /clearUploadAttentionRouteParams/);
  assert.match(webChat, /next\.delete\("uploadAttention"\)/);
  assert.match(webChat, /next\.delete\("uploadAttentionClientRequestId"\)/);
  assert.match(webChat, /next\.delete\("uploadAttentionNonce"\)/);
  assert.match(webChat, /data-upload-attention-id/);
  assert.match(webChat, /data-upload-attention-client-request-id/);
  assert.match(webChat, /uploadAttentionSelector\(uploadAttentionTargetId\)/);
  assert.match(webChat, /uploadAttentionClientRequestSelector\(attentionClientRequestId\)/);
  assert.match(webChat, /localClientRequestIdFromUploadAttention\(uploadAttentionTargetId\)/);
  assert.match(webChat, /clientUploadAttentionHighlightId\(attentionClientRequestId\)/);
  assert.match(webChat, /recoverSentServerMessageForClientRequestId/);
  assert.match(webChat, /\.eq\("sender_id", threadInvalidateScope\.currentUserId\)/);
  assert.match(webChat, /\.filter\("structured_payload->>client_request_id", "eq", clientRequestId\)/);
  assert.match(webChat, /patchedServerMessage = patchResult\.patched/);
  assert.match(webChat, /if \(serverMessageIds\.size > 0 && !patchedServerMessage\)/);
  assert.match(webChat, /await refetchChat\(\)/);
  assert.match(webChat, /if \(!recoveredSentMessage\) await runVibeClipRecoverySweepForThread\("foreground"\)/);
  assert.match(webChat, /isMessageDisplayReadyForOutboxCompletion\(message\)/);
  assert.match(webChat, /completedClientRequestIds\.add\(clientRequestId\)/);
  assert.match(webChat, /reconcileWebOutboxWithServerMessages\(\{ serverMessageIds, completedClientRequestIds \}\)/);
  assert.match(webChat, /uploadAttentionRecoveryAttemptedKeyRef/);
  assert.match(webChat, /uploadAttentionRecoveryPendingKeyRef/);
  assert.match(webChat, /scrollIntoView\(\{ behavior: "smooth", block: "center" \}\)/);
  assert.match(webChat, /That upload was already cleared or sent/);
  assert.match(webOutboxContext, /trackVibeClipEvent\("clip_recovery_status"/);
  assert.match(webOutboxContext, /trigger,\s+outcome: recoverySweepOutcome/);
  assert.match(webOutboxContext, /provider_unreachable_count: providerUnreachableCount/);
  assert.match(webOutboxContext, /if \(syncedStatus === "ready"\) \{[\s\S]{0,160}selfHealedCount \+= 1;/);
  assert.match(webOutboxContext, /trackVibeClipEvent\("media_upload_suspended_recovery", mediaUploadSuspendedRecoveryTelemetry\(\{[\s\S]{0,220}recoveryOutcome: "self_healed"/);
  assert.match(webOutboxContext, /recoveryOutcome: "self_healed"[\s\S]{0,520}updatedAt: upload\.updatedAt/);
  assert.match(webOutboxContext, /recoveryOutcome: "self_healed"[\s\S]{0,520}continue;/);
  assert.doesNotMatch(webOutboxContext, /syncedStatus === "ready" \|\| syncedStatus === "failed"/);
  assert.match(webOutboxContext, /retryVibeClipUpload/);
  assert.match(webOutboxContext, /\.from\("chat_vibe_clip_uploads"\)/);
  assert.match(webOutboxContext, /selectStaleUploadRows\(\["uploading", "processing"\], VIBE_CLIP_RECOVERY_SWEEP_LIMIT\)/);
  assert.match(webOutboxContext, /selectStaleUploadRows\(\s+\["failed"\]/);
  assert.match(webOutboxContext, /if \(failedResult\.error\) \{[\s\S]{0,260}checked_count: recoverableRows\.length[\s\S]{0,160}\} else \{[\s\S]{0,120}rows = \[\.\.\.recoverableRows, \.\.\.failedRows\]/);
  assert.match(webOutboxContext, /failedTopUpQueryFailed && upload\.status === "failed"[\s\S]{0,100}nextById\.set\(upload\.id, upload\)/);
  assert.match(webOutboxContext, /\.is\("published_message_id", null\)/);
  assert.match(webOutboxContext, /\.is\("recovery_dismissed_at", null\)/);
  assert.match(webChat, /getOutboxBlob\(item\.payload\.blobKey\)/);
  assert.match(webOutboxContext, /item\.payload\.kind === "video" && \(dueForCheck \|\| pastDeadline\)/);
  assert.match(webOutboxContext, /clientRequestId: item\.id/);
  assert.match(webOutboxContext, /serverMessageId = synced\.messageId/);
  assert.match(webChat, /dismissResult === "already_published"[\s\S]{0,180}refreshThreadAfterVibeClipRecoverySweep/);
  assert.match(webChat, /Could not clear the saved upload yet/);

  assert.match(webVideoBubble, /w-\[min\(17\.5rem,calc\(100svw-4rem\)\)\] max-w-full/);
  assert.doesNotMatch(webVideoBubble, /100vw|w-screen/);
  assert.match(webVideoBubble, /<AspectRatio ratio=\{9 \/ 16\}>/);
  assert.match(webVideoBubble, /w-full h-full object-cover bg-black/);
  assert.match(webVideoBubble, /aria-label=\{isMuted \? "Unmute video" : "Mute video"\}/);
  assert.match(webVideoBubble, /aria-label="Open video full screen"/);
  assert.match(webVideoLightbox, /void refreshMedia\(\)\.then\(\(didRefresh\) => \{[\s\S]{0,120}if \(!didRefresh\) setPhase\("error"\)/);
  assert.match(webVideoLightbox, /setPhase\("error"\);[\s\S]{0,80}return;/);
  assert.doesNotMatch(webVideoLightbox, /onWaiting=\{\(\) => setPhase\("loading"\)\}/);
  assert.match(webVideoLightbox, /onAutoplayBlocked: revealPlayer/);
  assert.match(webVideoLightbox, /CLIP_PLAYBACK_LOAD_TIMEOUT_MS/);
  assert.match(webVideoLightbox, /phase !== "loading" \|\| !canMountPlayer/);
  assert.match(webVideoLightbox, /const timeoutId = window\.setTimeout\(\(\) => \{[\s\S]{0,80}revealPlayer\(\);/);

  assert.match(nativeChat, /const MEDIA_CARD_MIN_WIDTH = 150/);
  assert.match(nativeChat, /const MEDIA_CARD_MAX_WIDTH = 280/);
  assert.match(nativeChat, /function getAdaptiveChatMediaWidth/);
  assert.match(nativeChat, /windowWidth - layout\.containerPadding \* 2 - 92/);
  assert.match(nativeChat, /Math\.min\(MEDIA_CARD_MAX_WIDTH, Math\.floor\(availableThreadWidth \* 0\.92\)\)/);
  assert.match(nativeChat, /styles\.mediaContentWrap, \{ width: mediaCardWidth \}/);

  assert.match(nativeVibeClipCard, /width: '100%'/);
  assert.match(nativeVibeClipCard, /const INLINE_CLIP_MIN_ASPECT_RATIO = 0\.78/);
  assert.match(nativeVibeClipCard, /Math\.max\(INLINE_CLIP_MIN_ASPECT_RATIO, Math\.min\(INLINE_CLIP_MAX_ASPECT_RATIO, meta\.aspectRatio\)\)/);
  assert.match(nativeVibeClipCard, /style=\{\[styles\.videoWrap, \{ aspectRatio: cardAspectRatio, maxHeight: INLINE_CLIP_MAX_HEIGHT \}\]\}/);
  assert.match(nativeVibeClipCard, /contentFit="cover"/);
  assert.match(nativeVibeClipCard, /shouldMountPlayer/);
  assert.match(nativeVibeClipCard, /type ClipPreviewState/);
  assert.match(nativeVibeClipCard, /syncChatVibeClipUploadStatus/);
  assert.match(nativeVibeClipCard, /const shouldAutoSyncProcessingStatus =/);
  assert.match(nativeVibeClipCard, /clientRequestId: effectiveClientRequestId/);
  assert.match(nativeVibeClipCard, /CHAT_VIBE_CLIP_STATUS_SYNC_SAFETY_NET_INTERVAL_MS = 30_000/);
  assert.doesNotMatch(nativeVibeClipCard, /CHAT_VIBE_CLIP_STATUS_SYNC_DELAY_MS/);
  assert.doesNotMatch(nativeVibeClipCard, /CHAT_VIBE_CLIP_STATUS_SYNC_FAST_INTERVAL_MS/);
  assert.match(nativeVibeClipCard, /statusSyncInFlightRef/);
  assert.match(nativeVibeClipCard, /statusSyncRunIdRef/);
  assert.match(nativeVibeClipCard, /isMountedRef\.current = true/);
  assert.match(nativeVibeClipCard, /if \(statusSyncInFlightRef\.current\) return/);
  assert.match(nativeVibeClipCard, /testID="vibe-clip-recovery-panel"/);
  assert.match(nativeVibeClipCard, /testID="vibe-clip-resume-upload"/);
  assert.match(nativeVibeClipCard, /testID="vibe-clip-discard-send-again"/);
  assert.match(nativeVibeClipCard, /testID="vibe-clip-check-status"/);
  assert.match(nativeChat, /buildVibeClipRecovery/);
  assert.match(nativeChat, /vibeClipRecoveryFromDecision/);
  assert.match(nativeChat, /trackVibeClipEvent\('clip_recovery_status'/);
  assert.match(nativeChat, /outcome: decision\.telemetryOutcome/);
  assert.doesNotMatch(nativeChat, /function vibeClipRecoveryForOutboxItem/);
  assert.match(nativeChat, /retryVibeClipUpload\(outboxItemId, strategy\)/);
  assert.match(nativeChat, /remove\(outboxItemId\);[\s\S]{0,500}openVideoMessageOptions\(\)/);
  assert.match(nativeVibeClipCard, /void refreshClipMedia\('preview'\)\.finally\(/);
  assert.match(nativeVibeClipCard, /POSTER_PREVIEW_RETRY_DELAYS_MS = \[1000, 3000, 8000\]/);
  assert.match(nativeVibeClipCard, /fallbackUrls: thumbnailFallbackUrls/);
  assert.match(nativeVibeClipCard, /uniqueDisplayablePosterUris\(playableThumbnailUrl, thumbnailFallbackUrls\)/);
  assert.match(nativeVibeClipCard, /if \(state === 'failed'\)/);
  assert.match(nativeVibeClipCard, /onPosterPreviewStateChange\?\.\('unknown', nextUrl\)/);
  assert.match(nativeVibeClipCard, /onResolvedThumbnailUrl\?\.\(nextUrl\)/);
  assert.doesNotMatch(nativeVibeClipCard, /if \(didRefresh\) posterRefreshAttemptedForRef\.current = null/);
  assert.match(nativeVibeClipCard, /resolveMediaFallbackCopy/);
  assert.match(nativeVibeClipCard, /fallbackCopy\.title/);
  assert.match(nativeVibeClipCard, /unavailableCopy\.title/);
  assert.doesNotMatch(nativeVibeClipCard, /Tap to play/);
  assert.doesNotMatch(nativeVibeClipCard, /Loading clip/);
  assert.match(nativeVibeClipCard, /const \[hasPlayed, setHasPlayed\] = useState\(false\)/);
  assert.match(nativeVibeClipCard, /if \(ev\.isPlaying\) setHasPlayed\(true\)/);
  assert.doesNotMatch(nativeVibeClipCard, /setPlayRequested\(true\);\s*setHasPlayed\(true\)/);
  assert.doesNotMatch(nativeVibeClipCard, /const showPreviewLoader/);
  assert.match(nativeVibeClipCard, /posterPreviewState\?: VibeClipPosterPreviewState/);
  assert.match(
    nativeVibeClipCard,
    /onPosterPreviewStateChange\?: \(state: VibeClipPosterPreviewState, thumbnailUrl\?: string \| null\) => void/,
  );
  assert.match(nativeVibeClipCard, /onLoad=\{\(\) => onPreviewStateChange\?\.\('ready', displayableUri\)\}/);
  assert.match(nativeVibeClipCard, /onPreviewStateChange\?\.\('failed', displayableUri\)/);
  assert.match(nativeVibeClipCard, /source=\{\{ uri: displayableUri \}\}/);
  assert.match(nativeVibeClipCard, /effectivePosterPreviewState === 'failed'/);
  assert.match(nativeVibeClipCard, /onRefreshClipMedia\('playback'\)/);
  assert.match(nativeVibeClipCard, /onRefreshClipMedia\('manual'\)/);
  assert.match(nativeVibeClipCard, /MAX_CLIP_PLAYBACK_REFRESH_ATTEMPTS = 2/);
  assert.match(nativeVibeClipCard, /PLAYBACK_REFRESH_RETRY_DELAY_MS = 650/);
  assert.match(nativeVibeClipCard, /getCachedMediaAssetFailureCode/);
  assert.match(nativeVibeClipCard, /isTransientMediaAssetFailureCode/);
  assert.match(nativeVibeClipCard, /if \(reason === 'preview'\) return refreshPoster\(\)/);
  assert.match(nativeVibeClipCard, /setPosterPreviewState\('unknown', displayableFreshThumbnailUri\)/);
  assert.match(nativeVibeClipCard, /posterRetryStateRef/);
  assert.match(nativeVibeClipCard, /playableVideoUrlRef/);
  assert.match(nativeVibeClipCard, /playableThumbnailUrlRef/);
  assert.match(nativeVibeClipCard, /requestImmersiveWithCurrentMedia/);
  assert.match(nativeVibeClipCard, /immersiveResolveInFlightRef/);
  assert.match(nativeVibeClipCard, /if \(!canOpenImmersive\)[\s\S]{0,320}onRefreshClipMedia\('initial'\)/);
  assert.match(nativeChat, /onRequestImmersive=\{\(media\) =>[\s\S]{0,180}uri: media\?\.videoUrl \?\? displayClipMeta\.videoUrl/);
  assert.match(nativeVibeClipCard, /isResolvableMediaRef\(playableThumbnailUrl\)/);
  assert.match(nativeVibeClipCard, /CLIP_PLAYBACK_LOAD_TIMEOUT_MS/);
  assert.doesNotMatch(nativeVibeClipCard, /player\.replace/);
  assert.match(nativeVibeClipCard, /vibeClip\.player\.status\.initial/);
  assert.match(nativeVibeClipCard, /onResetPlaybackRefreshAttempt/);
  assert.match(nativeVibeClipCard, /setHasError\(false\)/);
  assert.match(nativeVibeClipCard, /setInlinePlayRequestToken\(\(token\) => token \+ 1\)/);
  assert.match(nativeChat, /function vibeClipPosterCacheKey/);
  assert.match(nativeChat, /vibeClipPosterPreviewByKey/);
  assert.match(nativeChat, /posterPreviewState=\{posterPreviewState\}/);
  assert.match(nativeChat, /onPosterPreviewStateChange=\{\(state, thumbnailUrl\) =>/);
  assert.match(nativeChat, /const shouldMountPlayer = videoViewer\?\.uri === displayClipMeta\.videoUrl/);
  assert.doesNotMatch(nativeChat, /visibleRowKeys\.has\(rowKey\)/);
  assert.match(nativeOutboxContext, /function recoverInterruptedSendingItems/);
  assert.match(nativeOutboxContext, /force: true/);
  assert.match(nativeOutboxContext, /activeProcessingIds: processingRef\.current/);
  assert.match(nativeChatMediaResolver, /export async function syncChatVibeClipUploadStatus/);
  assert.match(nativeChatMediaResolver, /uploadId: string \| null/);
  assert.match(nativeChatMediaResolver, /providerReachable: boolean/);
  assert.match(nativeChatMediaResolver, /providerError: string \| null/);
  assert.match(nativeChatMediaResolver, /clientRequestId\?: string \| null/);
  assert.match(nativeChatMediaResolver, /if \(isUuid\(clientRequestId\)\) body\.client_request_id = clientRequestId/);
  assert.match(nativeChatMediaResolver, /messageId: typeof payload\?\.message_id === 'string'/);
  assert.match(nativeOutboxContext, /syncChatVibeClipUploadStatus/);
  assert.match(nativeOutboxContext, /runVibeClipRecoverySweep/);
  assert.match(nativeOutboxRunner, /void sweep\('mount_sweep'\)/);
  assert.match(nativeOutboxRunner, /void sweep\('foreground'\)/);
  assert.match(nativeOutboxContext, /staleVibeClipUploadsForMatch/);
  assert.match(nativeOutboxContext, /staleVibeClipUploads,/);
  assert.match(nativeOutboxContext, /recoveryAttentionCount/);
  assert.match(nativeOutboxContext, /recoveryAttentionTargets/);
  assert.match(nativeOutboxContext, /buildRecoveryAttentionTargets\(items, staleVibeClipUploads\)/);
  assert.match(nativeOutboxContext, /recoveryAttentionTargets\.length/);
  assert.match(nativeOutboxContext, /reconcileWithServerMessages/);
  assert.match(nativeOutboxContext, /shouldPruneOutboxItemAfterServerReconcile/);
  assert.match(nativeOutboxContext, /dismissStaleVibeClipUpload/);
  assert.match(nativeOutboxContext, /dismiss-chat-vibe-clip-upload/);
  assert.match(nativeOutboxContext, /type VibeClipRecoveryDismissResult/);
  assert.match(nativeOutboxContext, /response\?\.success === true/);
  assert.match(nativeOutboxContext, /response\.already_published \? 'already_published' : 'dismissed'/);
  assert.match(nativeOutboxContext, /attachOtherUserIdsToStaleUploads/);
  assert.match(nativeOutboxContext, /validateRecoveryAttentionTarget/);
  assert.match(nativeOutboxContext, /skipRecoveryAttentionTarget/);
  assert.match(nativeOutboxContext, /normalizeServerRecoveryAttentionTarget\(target, upload\)/);
  assert.match(nativeLayout, /NativeUploadRecoveryGlobalBanner/);
  assert.match(nativeLayout, /uploads need attention/);
  assert.match(nativeLayout, /recoveryAttentionTargets/);
  assert.match(nativeLayout, /uploadAttentionTargetValidationKey/);
  assert.match(nativeLayout, /target\.status/);
  assert.match(nativeLayout, /target\.updatedAtMs/);
  assert.match(nativeLayout, /selectPrimaryRecoveryAttentionTarget\(visibleRecoveryAttentionTargets, currentOtherUserId\)/);
  assert.match(nativeLayout, /currentOtherUserId === null/);
  assert.match(nativeLayout, /try \{[\s\S]{0,120}result = await validateRecoveryAttentionTarget\(target\)/);
  assert.match(nativeLayout, /validateRecoveryAttentionTarget\(primaryTarget\)/);
  assert.match(nativeLayout, /skipRecoveryAttentionTarget\(primaryTarget\)/);
  assert.match(nativeLayout, /setHiddenAttentionTarget/);
  assert.doesNotMatch(nativeLayout, /setHiddenAttentionKey/);
  assert.match(nativeLayout, /uploadAttention: target\.attentionId/);
  assert.match(nativeLayout, /uploadAttentionClientRequestId: target\.clientRequestId/);
  assert.match(nativeLayout, /uploadAttentionNonce: String\(Date\.now\(\)\)/);
  assert.match(nativeLayout, />Skip</);
  assert.match(nativeLayout, /Review recovery options in chat/);
  assert.doesNotMatch(nativeLayout, /Review or recover from the saved upload queue/);
  assert.match(nativeChat, /uploadAttentionIdForThreadMessage/);
  assert.match(nativeChat, /clearUploadAttentionRouteParams/);
  assert.match(nativeChat, /router\.setParams\(\{[\s\S]{0,160}uploadAttention: undefined/);
  assert.match(nativeChat, /uploadAttentionClientRequestId: undefined/);
  assert.match(nativeChat, /uploadAttentionNonce: undefined/);
  assert.match(nativeChat, /threadMessageClientRequestId\(row\.message\) === attentionClientRequestId/);
  assert.match(nativeChat, /localClientRequestIdFromUploadAttention\(uploadAttentionTargetId\)/);
  assert.match(nativeChat, /clientUploadAttentionHighlightId\(attentionClientRequestId\)/);
  assert.match(nativeChat, /recoverSentServerMessageForClientRequestId/);
  assert.match(nativeChat, /\.eq\('sender_id', threadInvalidateScope\.currentUserId\)/);
  assert.match(nativeChat, /\.filter\('structured_payload->>client_request_id', 'eq', clientRequestId\)/);
  assert.match(nativeChat, /patchedServerMessage = patchResult\.patched/);
  assert.match(nativeChat, /if \(serverMessageIds\.size > 0 && !patchedServerMessage\)/);
  assert.match(nativeChat, /await refetch\(\)/);
  assert.match(nativeChat, /if \(!recoveredSentMessage\) await runVibeClipRecoverySweepForThread\('foreground'\)/);
  assert.match(nativeChat, /isMessageDisplayReadyForOutboxCompletion\(message\)/);
  assert.match(nativeChat, /completedClientRequestIds\.add\(clientRequestId\)/);
  assert.match(nativeChat, /reconcileWithServerMessages\(\{ serverMessageIds, completedClientRequestIds \}\)/);
  assert.match(nativeChat, /uploadAttentionRecoveryAttemptedKeyRef/);
  assert.match(nativeChat, /uploadAttentionRecoveryPendingKeyRef/);
  assert.match(nativeChat, /scrollToIndex\(\{ index, animated: true, viewPosition: 0\.5 \}\)/);
  assert.match(nativeChat, /That upload was already cleared or sent/);
  assert.match(nativeChat, /uploadAttentionHighlight/);
  assert.match(nativeOutboxContext, /trackVibeClipEvent\('clip_recovery_status'/);
  assert.match(nativeOutboxContext, /trigger,\s+outcome: recoverySweepOutcome/);
  assert.match(nativeOutboxContext, /provider_unreachable_count: providerUnreachableCount/);
  assert.match(nativeOutboxContext, /if \(syncedStatus === 'ready'\) \{[\s\S]{0,160}selfHealedCount \+= 1;/);
  assert.match(nativeOutboxContext, /trackVibeClipEvent\('media_upload_suspended_recovery', mediaUploadSuspendedRecoveryTelemetry\(\{[\s\S]{0,220}recoveryOutcome: 'self_healed'/);
  assert.match(nativeOutboxContext, /recoveryOutcome: 'self_healed'[\s\S]{0,520}updatedAt: upload\.updatedAt/);
  assert.match(nativeOutboxContext, /recoveryOutcome: 'self_healed'[\s\S]{0,520}continue;/);
  assert.doesNotMatch(nativeOutboxContext, /syncedStatus === 'ready' \|\| syncedStatus === 'failed'/);
  assert.match(nativeOutboxContext, /retryVibeClipUpload/);
  assert.match(nativeOutboxContext, /\.from\('chat_vibe_clip_uploads'\)/);
  assert.match(nativeOutboxContext, /selectStaleUploadRows\(\['uploading', 'processing'\], VIBE_CLIP_RECOVERY_SWEEP_LIMIT\)/);
  assert.match(nativeOutboxContext, /selectStaleUploadRows\(\s+\['failed'\]/);
  assert.match(nativeOutboxContext, /if \(failedResult\.error\) \{[\s\S]{0,260}checked_count: recoverableRows\.length[\s\S]{0,160}\} else \{[\s\S]{0,120}rows = \[\.\.\.recoverableRows, \.\.\.failedRows\]/);
  assert.match(nativeOutboxContext, /failedTopUpQueryFailed && upload\.status === 'failed'[\s\S]{0,100}nextById\.set\(upload\.id, upload\)/);
  assert.match(nativeOutboxContext, /\.is\('published_message_id', null\)/);
  assert.match(nativeOutboxContext, /\.is\('recovery_dismissed_at', null\)/);
  assert.match(nativeChat, /FileSystem\.getInfoAsync\(item\.payload\.uri\)/);
  assert.match(nativeOutboxContext, /item\.payload\.kind === 'video' && \(dueForCheck \|\| pastDeadline\)/);
  assert.match(nativeOutboxContext, /clientRequestId: item\.id/);
  assert.match(nativeOutboxContext, /serverMessageId = synced\.messageId/);
  assert.match(nativeChat, /dismissResult === 'already_published'[\s\S]{0,180}refreshThreadAfterVibeClipRecoverySweep/);
  assert.match(nativeChat, /Couldn’t clear upload/);
});

test("web pending Vibe Clip uploads avoid generic video errors and dedupe success toasts", () => {
  assert.match(webChat, /function isPendingVibeClipOutboxItem/);
  assert.match(webChat, /function pendingVibeClipMetaFromOutboxItem/);
  assert.match(webChat, /const pendingClipMeta = useMemo/);
  assert.match(webChat, /const displayClipMeta = clipMeta \?\? pendingClipMeta/);
  assert.match(webChat, /displayClipMeta \? \(/);
  assert.match(webChat, /outboxClipSentToastIdsRef/);
  assert.match(webChat, /!outboxClipSentToastIdsRef\.current\.has\(it\.id\)/);
  assert.match(webChat, /outboxClipSentToastIdsRef\.current\.add\(it\.id\)/);
  assert.match(webChat, /toast\.success\(VIBE_CLIP_TOAST_SENT, \{ id: `vibe-clip-sent:\$\{it\.id\}` \}\)/);
  assert.match(webVibeClipBubble, /const isUploadPendingStatus = processingStatus === "uploading" \|\| processingStatus === "processing"/);
  assert.match(webVibeClipBubble, /const isServerProcessing = isUploadPendingStatus && !isLocalPreview/);
  assert.match(webVibeClipBubble, /const shouldAutoSyncProcessingStatus = isServerProcessing;/);
  assert.doesNotMatch(webVibeClipBubble, /shouldAutoSyncProcessingStatus =[\s\S]{0,140}videoSourceRef \|\| thumbnailSourceRef/);
  assert.match(webVibeClipBubble, /const handleVideoLoadError = useCallback/);
  assert.match(
    webVibeClipBubble,
    /if \(isLocalPreview && isUploadPendingStatus\) \{[\s\S]{0,260}setPlayableVideoUrl\(""\)[\s\S]{0,220}setLoadError\(false\)/,
  );
  assert.match(webVibeClipBubble, /const shouldShowLoadError = loadError && !isUploadPendingStatus/);
  assert.match(webVibeClipBubble, /if \(shouldShowLoadError \|\| isProcessingFailed\)/);
  assert.match(webVibeClipBubble, /onError=\{handleVideoLoadError\}/);
});

test("native pending Vibe Clip local preview failures stay in preparing state", () => {
  assert.match(nativeVibeClipCard, /function isUploadPendingStatus\(status: VibeClipDisplayMeta\['processingStatus'\]\): boolean/);
  assert.match(nativeVibeClipCard, /function isPendingLocalPreviewClip/);
  assert.match(nativeVibeClipCard, /const isPendingLocalPreview = isPendingLocalPreviewClip\(meta\)/);
  assert.match(nativeVibeClipCard, /const handlePendingLocalPreviewFailure = useCallback/);
  assert.match(
    nativeVibeClipCard,
    /if \(isPendingLocalPreview\) \{[\s\S]{0,140}handlePendingLocalPreviewFailure\(\)/,
  );
  assert.match(nativeVibeClipCard, /const localPreviewUnavailableForRef = useRef<string \| null>\(null\)/);
  assert.match(
    nativeVibeClipCard,
    /localPreviewUnavailableForRef\.current = currentPreviewUri[\s\S]{0,140}setPlayableVideoUrl\(''\)/,
  );
  assert.match(
    nativeVibeClipCard,
    /const nextVideoUrl = localPreviewUnavailableForRef\.current === meta\.videoUrl \? '' : meta\.videoUrl/,
  );
  assert.match(nativeVibeClipCard, /const shouldAutoSyncProcessingStatus = isSyncableServerProcessing;/);
  assert.doesNotMatch(nativeVibeClipCard, /shouldAutoSyncProcessingStatus =[\s\S]{0,140}videoSourceRef \|\| thumbnailSourceRef/);
  assert.match(nativeVibeClipCard, /const isProcessing = isServerProcessingClip\(resolvedMeta\)/);
  assert.match(
    nativeVibeClipCard,
    /const reason = resolveNativeMediaPlaybackFallbackReason\(\{ uri: meta\.videoUrl, error: payload \}\);/,
  );
  assert.match(
    nativeVibeClipCard,
    /if \(!didRefresh\) \{[\s\S]{0,80}setFallbackReason\(reason\);[\s\S]{0,80}setHasError\(true\);/,
  );
  assert.match(
    nativeVibeClipCard,
    /if \(!didRefresh\) \{[\s\S]{0,120}setFallbackReason\(resolveNativeMediaPlaybackFallbackReason\(\{ uri: meta\.videoUrl \}\)\);[\s\S]{0,80}setHasError\(true\);/,
  );
});

test("native chat validates library and camera video before enqueue", () => {
  assert.match(nativeChat, /function imagePickerDurationSeconds/);
  assert.match(nativeChat, /return durationMs \/ 1000/);
  assert.match(nativeChat, /shouldDownloadFromNetwork: true/);
  assert.match(nativeChat, /videoMaxDuration: VIBE_CLIP_MAX_DURATION_SEC/);
  assert.match(nativeChat, /durationSec == null[\s\S]{0,80}VIBE_CLIP_UPLOAD_DURATION_UNREADABLE/);
  assert.match(nativeChat, /durationSec > VIBE_CLIP_MAX_DURATION_SEC \+ 0\.25/);
  assert.match(nativeChat, /sizeBytes === 0[\s\S]{0,120}cleanupOutboxCacheUri/);
  assert.match(nativeChat, /sizeBytes > VIBE_CLIP_MAX_SOURCE_BYTES/);
  assert.match(nativeChat, /VIBE_CLIP_UPLOAD_LARGE_SOFT_WARNING/);
  assert.match(nativeChat, /function NativeVibeClipCameraModal/);
  assert.match(nativeChat, /CameraView/);
  assert.match(nativeChat, /recordAsync/);
  assert.match(nativeChat, /useNativeCaptionCapture/);
  assert.match(nativeChat, /aspectRatioForVideoAsset\(asset\)/);
});

test("native upload and cache keep mobile video formats intact", () => {
  assert.doesNotMatch(nativeUpload, /uploadChatVideoMessage/);
  assert.doesNotMatch(nativeUpload, /upload-chat-video/);
  assert.equal(existsSync(join(root, "apps/mobile/lib/chatVibeClipThumbnail.ts")), false);
  assert.match(nativeOutboxExecute, /completePublishedChatVibeClipUpload/);
  assert.match(nativeOutboxExecute, /captions: payload\.captions \?\? null/);
  assert.match(nativeOutboxExecute, /ChatVibeClipUploadedButUnpublishedError/);
  assert.match(nativeOutboxExecute, /isBunnyStreamPlaybackRef\(item\.uploadedMediaUrl\)/);
  assert.match(nativeOutboxExecute, /bunnyStreamVideoIdFromRef\(trimmed\)/);
  assert.match(nativeStreamUpload, /new tus\.Upload\(rnFileSource as unknown as File/);
  assert.match(nativeStreamUpload, /uploadSize: params\.fileSize/);
  assert.match(nativeStreamUpload, /upload\.findPreviousUploads\(\)/);
  assert.match(nativeStreamUpload, /getFreshCachedAccessToken/);
  assert.match(nativeStreamUpload, /headers: \{ Authorization: `Bearer \$\{params\.accessToken\}` \}/);
  assert.match(nativeStreamUpload, /class ChatVibeClipUploadedButUnpublishedError/);
  assert.match(nativeStreamUpload, /completePublishedChatVibeClipUpload/);
  assert.match(nativeStreamUpload, /bunnyStreamVideoIdFromRef\(params\.playbackRef\)/);
  assert.match(nativeStreamUpload, /const originalExt = extensionFromUri\(params\.uri\) \|\| null/);
  assert.match(nativeStreamUpload, /stableUploadFileUri\(params\.uri, params\.clientRequestId, originalExt\)/);
  assert.match(nativeStreamUpload, /mimeFromExtension\(originalExt \?\? '', params\.mimeType\)/);
  assert.match(nativeStreamUpload, /const completionToken = await getFreshCachedAccessToken\(\)/);
  assert.doesNotMatch(nativeStreamUpload, /extensionFromUri\(stable\.uri\) \|\| 'mp4'/);
  assert.match(nativeStreamUpload, /created\.status === 'failed'/);
  assert.match(nativeStreamUpload, /!created\.status \|\| created\.status === 'uploading'/);
  assert.match(
    nativeStreamUpload,
    /isStaleTusCredentialError[\s\S]+captions: params\.captions[\s\S]+refreshed\.videoId/,
  );
  assert.match(nativeStreamUpload, /if \(!mimeType\) throw new Error\(VIBE_CLIP_UPLOAD_INVALID_TYPE\)/);
  assert.match(nativeStreamUpload, /return null/);
  assert.match(nativeStreamUpload, /create-chat-vibe-clip-upload/);
  assert.match(nativeStreamUpload, /complete-chat-vibe-clip-upload/);
  assert.match(nativeStreamUpload, /info\.size > VIBE_CLIP_MAX_SOURCE_BYTES/);
  assert.match(nativeUpload, /const GENERIC_UPLOAD_MIME_TYPE = 'application\/octet-stream'/);
  assert.match(nativeStreamUpload, /mimeType === 'video\/quicktime'[\s\S]{0,120}return 'mov'/);
  assert.match(nativeStreamUpload, /mimeType === 'video\/x-m4v'[\s\S]{0,120}return 'm4v'/);
  assert.match(nativeStreamUpload, /mimeType === 'video\/webm'[\s\S]{0,120}return 'webm'/);
  assert.match(nativeChat, /mimeForPayload\('video', asset\.mimeType \?\? null, asset\.fileName \?\? asset\.uri\)/);
  assert.doesNotMatch(nativeChat, /asset\.mimeType \?\? 'video\/mp4'/);
  assert.match(nativeMediaCache, /mimeForPayload\('video'/);
  assert.match(nativeMediaCache, /normalized\?\.includes\('x-m4v'\)[\s\S]{0,120}return 'm4v'/);
  assert.match(nativeMediaCache, /normalized\?\.includes\('webm'\)[\s\S]{0,120}return 'webm'/);
  assert.match(nativeMediaCache, /\['mov', 'm4v', 'webm', 'mp4', 'mkv', 'avi', 'wmv', 'flv', 'ts', 'mpeg', 'mpg'\]\.includes/);
  assert.match(nativeMediaCache, /if \(ext === 'jpg' \|\| ext === 'jpeg'\) return 'jpg';[\s\S]{0,80}return 'bin'/);
  assert.doesNotMatch(nativeMediaCache, /return 'mp4';\n\s*\}/);
});

test("server upload and publish paths enforce Bunny Stream Vibe Clip limits", () => {
  assert.match(uploadChatVideo, /const CHAT_VIDEO_MAX_UPLOAD_BYTES = 8 \* 1024 \* 1024/);
  assert.match(uploadChatVideo, /Supabase Edge Function ~10MB request-body cap/);
  assert.match(uploadChatVideo, /Maximum 8MB/);
  assert.match(chatVibeClipShared, /BUNNY_CHAT_STREAM_LIBRARY_ID/);
  assert.match(chatVibeClipShared, /\[89ab\]\[0-9a-f\]\{3\}-\[0-9a-f\]\{12\}/);
  assert.match(createChatVibeClipUpload, /createTusSignature/);
  assert.match(createChatVibeClipUpload, /registerMediaAsset/);
  assert.match(createChatVibeClipUpload, /\.from\("chat_vibe_clip_uploads"\)/);
  assert.match(createChatVibeClipUpload, /existing\.data\.match_id !== matchId/);
  assert.match(createChatVibeClipUpload, /client_request_id_conflict/);
  assert.match(createChatVibeClipUpload, /dismissed_upload_reuse_rejected/);
  assert.match(createChatVibeClipUpload, /upload_dismissed/);
  assert.match(createChatVibeClipUpload, /queueCreatedVideoOrphanCleanup/);
  assert.match(createChatVibeClipUpload, /enqueue_media_delete/);
  assert.match(createChatVibeClipUpload, /cleanup_queued/);
  assert.match(createChatVibeClipUpload, /last_error: reason/);
  assert.doesNotMatch(createChatVibeClipUpload, /legacy_table: "chat_vibe_clip_uploads"/);
  assert.doesNotMatch(createChatVibeClipUpload, /legacy_id: reason/);
  assert.match(createChatVibeClipUpload, /\.in\("status", \["uploading", "soft_deleted", "failed"\]\)[\s\S]+\.select\("id"\)[\s\S]+\.maybeSingle\(\)/);
  assert.match(createChatVibeClipUpload, /media_asset_orphan_mark_skipped/);
  assert.match(completeChatVibeClipUpload, /ensureChatVibeClipMessage/);
  assert.match(completeChatVibeClipUpload, /data\.client_request_id !== clientRequestId/);
  assert.match(completeChatVibeClipUpload, /client_request_id_conflict/);
  assert.match(completeChatVibeClipUpload, /upload\.status === "ready" && status !== "ready"/);
  assert.match(completeChatVibeClipUpload, /upload\.status === "failed" && status === "processing"/);
  assert.match(completeChatVibeClipUpload, /bunny_processing_failed_status_update_failed/);
  assert.match(completeChatVibeClipUpload, /providerReachable/);
  assert.match(completeChatVibeClipUpload, /provider_unavailable/);
  assert.match(completeChatVibeClipUpload, /media_provider_unreachable/);
  assert.match(completeChatVibeClipUpload, /provider_reachable: false/);
  assert.match(completeChatVibeClipUpload, /dismissed_upload_publish_rejected/);
  assert.match(completeChatVibeClipUpload, /upload_dismissed/);
  assert.match(dismissChatVibeClipUpload, /dismiss-chat-vibe-clip-upload/);
  assert.match(dismissChatVibeClipUpload, /\.eq\("sender_id", user\.id\)/);
  assert.match(dismissChatVibeClipUpload, /\.is\("published_message_id", null\)/);
  assert.match(dismissChatVibeClipUpload, /\.is\("recovery_dismissed_at", null\)/);
  assert.match(dismissChatVibeClipUpload, /\.select\("id, match_id, sender_id, client_request_id, status, published_message_id, recovery_dismissed_at"\)/);
  assert.match(dismissChatVibeClipUpload, /findExistingMessageForUpload/);
  assert.match(dismissChatVibeClipUpload, /already_published_message_found/);
  assert.match(dismissChatVibeClipUpload, /concurrent_publish_won/);
  assert.match(dismissChatVibeClipUpload, /concurrent_publish_message_found/);
  assert.match(dismissChatVibeClipUpload, /dismiss_not_applied/);
  assert.match(dismissChatVibeClipUpload, /recovery_dismissed_at/);
  assert.match(dismissChatVibeClipUpload, /already_published/);
  assert.match(dismissChatVibeClipUpload, /idempotent_replay/);
  assert.match(supabaseConfig, /\[functions\.dismiss-chat-vibe-clip-upload\][\s\S]{0,40}verify_jwt = true/);
  assert.match(syncChatVibeClipStatus, /sync-chat-vibe-clip-status/);
  assert.match(syncChatVibeClipStatus, /providerReachable/);
  assert.match(syncChatVibeClipStatus, /media_provider_unreachable/);
  assert.match(syncChatVibeClipStatus, /provider_reachable: false/);
  assert.match(webStreamUpload, /resumePrevious\?: boolean/);
  assert.match(webStreamUpload, /params\.resumePrevious !== false && previousUploads\.length/);
  assert.match(webStreamUpload, /const shouldResumePreviousUpload = tusHttpStatus\(error\) !== 410/);
  assert.match(webStreamUpload, /resumePrevious: shouldResumePreviousUpload/);
  assert.match(nativeStreamUpload, /resumePrevious\?: boolean/);
  assert.match(nativeStreamUpload, /params\.resumePrevious !== false && previousUploads\.length/);
  assert.match(nativeStreamUpload, /const shouldResumePreviousUpload = tusHttpStatus\(error\) !== 410/);
  assert.match(nativeStreamUpload, /resumePrevious: shouldResumePreviousUpload/);
  assert.match(chatVibeClipShared, /CHAT_VIBE_CLIP_MAX_DURATION_MS = 30_000/);
  assert.match(chatVibeClipShared, /CHAT_VIBE_CLIP_DURATION_TOLERANCE_MS = 250/);
  assert.match(chatVibeClipShared, /CHAT_VIBE_CLIP_MAX_SOURCE_BYTES = 200 \* 1024 \* 1024/);
  assert.match(chatVibeClipShared, /mapBunnyStatusToChatClipStatus/);
  assert.match(chatVibeClipShared, /published_message_lookup_failed/);
  assert.match(chatVibeClipShared, /\.eq\("id", upload\.published_message_id\)[\s\S]+\.eq\("message_kind", "vibe_clip"\)/);
  assert.match(chatVibeClipShared, /idempotent_message_lookup_failed/);
  assert.match(chatVibeClipShared, /\.eq\("message_kind", "vibe_clip"\)[\s\S]+client_request_id/);
  assert.match(chatVibeClipShared, /message_insert_duplicate_requery/);
  assert.match(chatVibeClipShared, /error\?\.code === "23505"/);
  assert.match(chatVibeClipShared, /\.from\("media_references"\)[\s\S]+\.eq\("is_active", true\)[\s\S]+\.limit\(1\)[\s\S]+\.maybeSingle\(\)/);
  assert.match(chatVibeClipShared, /function shouldIgnoreProviderStatus/);
  assert.match(chatVibeClipShared, /currentStatus === "ready" && nextStatus !== "ready"/);
  assert.match(chatVibeClipShared, /upload_publish_preflight_rejected/);
  assert.match(chatVibeClipShared, /upload_publish_state_update_skipped_dismissed/);
  assert.match(chatVibeClipShared, /cleanupInsertedMessageAfterDismissedPublish/);
  assert.match(chatVibeClipShared, /releaseMediaReference/);
  assert.match(chatVibeClipShared, /released_reference_count/);
  assert.match(chatVibeClipShared, /\.is\("recovery_dismissed_at", null\)[\s\S]+upload_publish_state_update_failed/);
  assert.match(chatVibeClipShared, /uploadUpdateError\?\.message \?\? "upload_publish_state_update_missing"/);
  assert.match(
    chatVibeClipShared,
    /provider_status_update_failed[\s\S]+return \{ handled: true, error: statusUpdateError\.message \}/,
  );
  assert.match(
    chatVibeClipShared,
    /provider_failed_message_update_failed[\s\S]+return \{ handled: true, error: messageUpdateError\.message \}/,
  );
  assert.match(chatVibeClipShared, /provider: "bunny_stream"/);
  assert.match(chatVibeClipShared, /failOnIgnoredNonReady\?: boolean/);
  assert.match(chatVibeClipShared, /!options\.publishIfProcessing/);
  assert.match(chatVibeClipShared, /function isTerminalChatVibeClipStatus/);
  assert.match(chatVibeClipShared, /shouldIgnoreProviderStatus\(upload\.status, status\)/);
  assert.match(chatVibeClipShared, /dismissed_provider_status_ignored/);
  assert.match(chatVibeClipShared, /upload\.recovery_dismissed_at && !upload\.published_message_id/);
  assert.match(chatVibeClipShared, /ignoredProviderStatus\?: boolean/);
  assert.match(chatVibeClipShared, /options\.failOnIgnoredNonReady[\s\S]+status !== "ready"/);
  assert.match(chatVibeClipShared, /ignoredProviderStatus: true/);
  assert.match(getChatMediaUrl, /BUNNY_CHAT_STREAM_CDN_HOSTNAME/);
  assert.match(getChatMediaUrl, /BUNNY_CHAT_STREAM_TOKEN_SECURITY_KEY/);
  assert.match(getChatMediaUrl, /fileName: mediaKind === "thumbnail" \? "thumbnail\.jpg" : "playlist\.m3u8"/);
  assert.match(getChatMediaUrl, /const previewUrl = await signBunnyStreamDirectoryUrl[\s\S]{0,260}fileName: "preview\.webp"/);
  assert.match(getChatMediaUrl, /const fallbackUrls = mediaKind === "thumbnail" \? \[previewUrl\] : \[\]/);
  assert.match(getChatMediaUrl, /const posterFallbackUrls = mediaKind === "thumbnail" \? \[\] : \[previewUrl\]/);
  assert.doesNotMatch(getChatMediaUrl, /async function hmacSha256Base64Url/);
  assert.match(getChatMediaUrl, /signBunnyStreamDirectoryUrl/);
  assert.match(bunnyStreamTokens, /const signingData = sortedSigningData\(\{ token_path: tokenPath \}\)/);
  assert.match(bunnyStreamTokens, /const token = `HS256-\$\{await signPayload/);
  assert.match(bunnyStreamTokens, /`\$\{tokenPath\}\$\{params\.expires\}\$\{signingData\}`/);
  assert.match(bunnyStreamTokens, /bcdn_token=\$\{token\}&expires=\$\{params\.expires\}&token_path=\$\{encodeURIComponent\(tokenPath\)\}/);
  assert.match(getChatMediaUrl, /playbackKind: mediaKind === "thumbnail" \? "progressive" : "hls"/);
  assert.match(getChatMediaUrl, /expiresInSeconds: TOKEN_TTL_SECONDS/);
  assert.match(videoWebhook, /BUNNY_CHAT_STREAM_LIBRARY_ID/);
  assert.match(videoWebhook, /allowedLibraryIds/);
  assert.match(videoWebhook, /const libraryIdRaw = VideoLibraryId == null \? null : String\(VideoLibraryId\)/);
  assert.match(videoWebhook, /const libraryIdTrimmed = libraryIdRaw == null \? null : libraryIdRaw\.trim\(\)/);
  assert.match(videoWebhook, /library_id: libraryIdTrimmed/);
  assert.match(videoWebhook, /library_id_raw: libraryIdRaw/);
  assert.match(videoWebhook, /logWebhook\("warn", "video_webhook_rejected", \{[\s\S]{0,160}reason: "library_mismatch"/);
  assert.match(videoWebhook, /updateChatVibeClipStatusByProvider/);
  assert.match(videoWebhook, /\{ publishIfProcessing: Status === 7 \}/);
  assert.doesNotMatch(videoWebhook, /failOnIgnoredNonReady: true/);
  assert.match(videoWebhook, /ignored_provider_status: chatClipResult\.ignoredProviderStatus === true/);
  assert.match(syncChatVibeClipStatus, /\{ publishIfProcessing: bunny\.rawStatus === 7 && upload\.sender_id === user\.id \}/);
  assert.match(chatThreadPage, /kind === "thumbnail" && asset\.provider === "bunny_stream" && asset\.media_family === "chat_video"/);
  assert.match(chatThreadPage, /function assetPriorityForKind\(asset: MediaAssetRow, kind: MediaKind\): number/);
  assert.match(chatThreadPage, /asset\.media_family === "chat_video_thumbnail"[\s\S]{0,120}return 2/);
  assert.match(chatThreadPage, /asset\.provider === "bunny_stream" && asset\.media_family === "chat_video"[\s\S]{0,120}return 1/);
  assert.match(chatThreadPage, /const shouldHydrateVideo =/);
  assert.match(chatThreadPage, /const durableThumbnailRef = \(shouldHydrateVideo \|\| !!next\.video_url\) \? durableAssetRef\(next\.id, "thumbnail"\) : null/);
  assert.match(chatThreadPage, /const effectiveThumbnailRef = durableThumbnailRef \?\? thumbnailRef/);
  assert.match(chatThreadPage, /payload\.thumbnail_url = effectiveThumbnailRef/);
  assert.match(chatThreadPage, /payload\.poster_ref = effectiveThumbnailRef/);
  assert.match(getChatMediaUrl, /if \(kind === "thumbnail"\) \{/);
  assert.match(getChatMediaUrl, /asset\.media_family === "chat_video_thumbnail"/);
  assert.match(getChatMediaUrl, /asset\.provider === "bunny_stream" && asset\.media_family === "chat_video"/);
  assert.match(getChatMediaUrl, /function assetMatchesSourceRef\(asset: MediaAssetRow, sourceRef: unknown\): boolean/);
  assert.match(getChatMediaUrl, /const sourceMatchedStorageThumbnail = assets\.find/);
  assert.match(getChatMediaUrl, /const explicitThumbnailAsset = assets\.find\(\(asset\) => asset\.media_family === "chat_video_thumbnail"\)/);
  assert.match(getChatMediaUrl, /const loadExactSourceAssets = async \(\): Promise<MediaAssetRow\[\]> =>/);
  assert.match(getChatMediaUrl, /const fallbackExplicitThumbnailAsset = await loadLatestExplicitThumbnailAsset\(\)/);
  assert.match(getChatMediaUrl, /const sourceRefTargetsStorageThumbnail =/);
  assert.match(getChatMediaUrl, /const exactSourceStreamAsset = exactStreamSourceAssets\.find\(\(asset\) => assetMatchesSourceRef\(asset, sourceRef\)\)/);
  assert.match(getChatMediaUrl, /const sourceMatchedStreamAsset = assets\.find\(\(asset\) => assetMatchesSourceRef\(asset, sourceRef\)\)/);
  assert.match(webMessagesHook, /deriveChatVideoThumbnailRef\(row\)/);
  assert.match(webMessagesHook, /Keep video playback lazy on chat open; thumbnails are the eager visual contract/);
  assert.match(webChat, /const effectiveThumbnailSourceRef = useMemo/);
  assert.match(webChat, /const posterUrl = displayChatVideoPosterUrlForMessage/);
  assert.match(webChat, /thumbnailUrl=\{posterUrl\}/);
  assert.match(webChat, /thumbnailSourceRef=\{effectiveThumbnailSourceRef\}/);
  assert.match(webChat, /thumbnailSourceRef: effectiveThumbnailSourceRef/);
  assert.match(webVideoBubble, /kind: "thumbnail"[\s\S]{0,160}onResolvedUrl: handleResolvedThumbnailUrl/);
  assert.match(webVideoBubble, /initialPlaybackResolveInFlightRef/);
  assert.match(webVideoBubble, /onResolvedThumbnailUrl\?: \(url: string\) => void/);
  assert.match(webVideoBubble, /onResolvedUrl: handleResolvedThumbnailUrl/);
  assert.match(webVideoBubble, /fallbackUrls: thumbnailFallbackUrls/);
  assert.match(webVideoBubble, /const handlePosterImageError = useCallback/);
  assert.match(webVideoBubble, /showPosterVisual && canMountPlayer && !showPreparingOverlay && !hasStartedPlayback/);
  assert.match(webVideoBubble, /onPlaying=\{handlePlaying\}/);
  assert.doesNotMatch(webVideoBubble, /const posterNotReady =\s*!isReady/);
  assert.match(webVideoBubble, /const isAwaitingPlaybackIntent = !canMountPlayer/);
  assert.match(webVideoBubble, /const showResolvingPlaybackOverlay = isAwaitingPlaybackIntent && playRequested && !loadError/);
  assert.match(webVideoBubble, /void refreshVideoUrlWithRetry\("initial", \{ bypassFailureCooldown: true \}\)/);
  assert.match(webVideoLightbox, /poster=\{visiblePosterUrl \?\? undefined\}/);
  assert.match(webVideoLightbox, /initialResolveRunIdRef/);
  assert.match(webVideoLightbox, /const \[hasStartedPlayback, setHasStartedPlayback\] = useState\(false\)/);
  assert.match(webVideoLightbox, /const showPosterProbe = !!visiblePosterUrl && !hasStartedPlayback && phase !== "error"/);
  assert.match(webVideoLightbox, /const showLoadingPosterOverlay = !!visiblePosterUrl && phase === "loading"/);
  assert.match(webVideoLightbox, /onPlaying=\{handlePlaying\}/);
  assert.match(webVideoLightbox, /onEnded=\{handleEnded\}/);
  assert.match(webVideoLightbox, /showPosterProbe \? \([\s\S]{0,260}onError=\{handlePosterImageError\}/);
  assert.match(webVideoLightbox, /posterFallbackResolveInFlightRef/);
  assert.match(webVideoLightbox, /posterFallbackResolveAttemptedForRef/);
  assert.match(webVideoLightbox, /const thumbnailSource = thumbnailSourceRef/);
  assert.match(webVideoLightbox, /const stableMessageId = messageId/);
  assert.match(webVideoLightbox, /const stableThumbnailSource = thumbnailSource/);
  assert.match(webVideoLightbox, /refreshResolvedMediaAsset\(stableMessageId, "thumbnail", stableThumbnailSource/);
  assert.match(webVideoLightbox, /asset\?\.fallbackUrls \?\? \[\]/);
  assert.match(webVideoLightbox, /setExtraPosterFallbackUrls/);
  assert.match(webVideoLightbox, /refreshedCurrentIndex === -1/);
  assert.match(webChatMediaResolver, /\{ messageId, mediaKind, sourceRef: rawRef/);
  assert.match(nativeChat, /deriveChatVideoThumbnailRef/);
  assert.match(nativeChatApi, /Keep video playback lazy on chat open; thumbnails are the eager visual contract/);
  assert.match(nativeChat, /const effectiveThumbnailSourceRef =/);
  assert.match(nativeChat, /const posterUri = displayChatVideoPosterUriForMessage/);
  assert.match(nativeChat, /thumbnailUri=\{posterUri\}/);
  assert.match(nativeChat, /thumbnailSourceRef=\{effectiveThumbnailSourceRef\}/);
  assert.match(nativeChat, /poster: posterUri/);
  assert.match(nativeChat, /kind: 'thumbnail'[\s\S]{0,160}autoResolve: true/);
  assert.match(nativeChat, /fallbackUrls: thumbnailFallbackUris/);
  assert.match(nativeChat, /uniqueDisplayableChatVideoPosterUris\(playablePosterUri, thumbnailFallbackUris\)/);
  assert.match(nativeChat, /CHAT_VIDEO_POSTER_PREVIEW_TIMEOUT_MS = 3500/);
  assert.match(nativeChat, /onLoad=\{onPosterLoad\}/);
  assert.match(nativeChat, /const freshPosterAsset = await refreshMediaAsset\(/);
  assert.match(nativeChat, /freshPosterAsset\?\.fallbackUrls \?\? \[\]/);
  assert.match(nativeChat, /const posterFallbackUris = uniqueDisplayableChatVideoPosterUris\(freshPosterAsset\?\.fallbackUrls \?\? \[\]\)/);
  assert.match(nativeChat, /posterFallbackUris: poster\.posterFallbackUris/);
  assert.match(nativeMediaViewer, /posterFallbackUris\?: string\[\] \| null/);
  assert.match(nativeMediaViewer, /posterRefreshAttemptedForUriRef/);
  assert.match(nativeMediaViewer, /const advancePosterCandidate = useCallback/);
  assert.match(nativeMediaViewer, /style=\{styles\.videoPosterProbe\}/);
  assert.match(nativeChat, /initialPlaybackResolveInFlightRef/);
  assert.match(nativeVibeClipCard, /initialPlaybackResolveInFlightRef/);
  assert.match(nativeVibeClipCard, /initialPlaybackResolveRunIdRef/);
  assert.match(nativeChat, /CHAT_VIDEO_POSTER_PREVIEW_RETRY_DELAYS_MS = \[1000, 3000, 8000\]/);
  assert.match(nativeChat, /type ChatVideoMediaRefreshReason = 'initial' \| 'playback' \| 'manual'/);
  assert.match(nativeChat, /shouldMountPlayer && isChatVideoPlaybackUri\(uri\) \? chatVideoSourceForUri\(uri\) : null/);
  assert.match(nativeChat, /const \[isResolvingInitialPlayback, setIsResolvingInitialPlayback\] = useState\(false\)/);
  assert.match(nativeChat, /initialPlaybackResolveFailed/);
  assert.match(nativeChat, /chat\.video\.status\.initial/);
  assert.doesNotMatch(nativeChat, /chat\.video\.pause\.unmount/);
  assert.match(nativeChat, /void refreshMediaUri\('initial', \{ bypassFailureCooldown: true \}\)/);
  assert.match(nativeChatMediaResolver, /\{ messageId, mediaKind, sourceRef: rawRef/);
  assert.match(nativeChatMediaResolver, /fallbackUrls: normalizePlayableUrlList\(payload\.fallbackUrls/);
  assert.match(nativeChatMediaResolver, /posterFallbackUrls: normalizePlayableUrlList\(payload\.posterFallbackUrls/);
  assert.match(nativeChatMediaResolver, /fallbackUrls: resolvedAsset\.posterFallbackUrls/);
  assert.match(nativeVibeClipCard, /kind: 'thumbnail'[\s\S]{0,160}autoResolve: true/);
  assert.match(chatVibeClipMigration, /CREATE TABLE IF NOT EXISTS public\.chat_vibe_clip_uploads/);
  assert.match(chatVibeClipMigration, /UNIQUE \(sender_id, client_request_id\)/);
  assert.match(chatVibeClipRecoveryDismissalMigration, /recovery_dismissed_at timestamptz/);
  assert.match(chatVibeClipRecoveryDismissalMigration, /idx_chat_vibe_clip_uploads_recovery_attention/);
  assert.match(chatVibeClipRecoveryDismissalMigration, /recovery_dismissed_at IS NULL/);
  assert.match(sendMessage, /const VIBE_CLIP_MAX_DURATION_MS = 30_000/);
  assert.ok(
    sendMessage.includes("chat-videos\\/([0-9a-fA-F-]{36})\\/([0-9a-fA-F-]{36})_"),
    "send-message should verify legacy upload-chat-video sender scope refs",
  );
  assert.match(sendMessage, /durationMs > VIBE_CLIP_MAX_DURATION_MS \+ VIBE_CLIP_DURATION_TOLERANCE_MS/);
  assert.match(sendMessage, /Video must be 30 seconds or shorter/);
  assert.match(sendMessage, /Math\.min\(VIBE_CLIP_MAX_DURATION_MS/);
});

test("Chat Vibe Clip P1.1 observability keeps stable trace fields", () => {
  assert.match(vibeClipAnalytics, /VIBE_CLIP_EVENTS = MEDIA_VIBE_CLIP_EVENTS/);
  assert.match(mediaTelemetry, /clip_recovery_status: "clip_recovery_status"/);
  assert.match(mediaTelemetry, /media_upload_suspended_recovery: "media_upload_suspended_recovery"/);
  assert.match(vibeClipRecovery, /would_benefit_from_background: true/);
  assert.match(webChat, /trackVibeClipEvent\("media_upload_suspended_recovery"/);
  assert.match(webOutboxContext, /trackVibeClipEvent\("media_upload_suspended_recovery"/);
  assert.match(nativeChat, /trackVibeClipEvent\('media_upload_suspended_recovery'/);
  assert.match(nativeOutboxContext, /trackVibeClipEvent\('media_upload_suspended_recovery'/);
  assert.match(createChatVibeClipUpload, /client_request_id: clientRequestId/);
  assert.match(createChatVibeClipUpload, /provider_object_id: videoId/);
  assert.match(createChatVibeClipUpload, /media_asset_registered/);

  assert.match(completeChatVibeClipUpload, /ChatVibeClipStatus/);
  assert.match(completeChatVibeClipUpload, /client_request_id: upload\.client_request_id/);
  assert.match(completeChatVibeClipUpload, /provider_object_id: upload\.provider_object_id/);
  assert.match(completeChatVibeClipUpload, /message_finalized/);

  assert.match(syncChatVibeClipStatus, /type MessageScopeRow/);
  assert.match(syncChatVibeClipStatus, /client_request_id: upload\.client_request_id/);
  assert.match(syncChatVibeClipStatus, /provider_object_id: upload\.provider_object_id/);
  assert.match(syncChatVibeClipStatus, /status_update_succeeded/);

  assert.match(videoWebhook, /import \* as Sentry from "https:\/\/deno\.land\/x\/sentry@8\.55\.0\/index\.mjs"/);
  assert.match(videoWebhook, /Sentry\.init\(\{/);
  assert.match(videoWebhook, /Sentry\.startSpan/);
  assert.match(videoWebhook, /let SENTRY_ENABLED = false/);
  assert.match(videoWebhook, /type CallbackOutcome<T>/);
  assert.match(videoWebhook, /let callbackStarted = false/);
  assert.match(videoWebhook, /let callbackOutcome: CallbackOutcome<T> \| null = null/);
  assert.match(videoWebhook, /if \(!callbackStarted\) return await callback\(\)/);
  assert.match(videoWebhook, /function unwrapCallbackOutcome<T>/);
  assert.match(videoWebhook, /if \(!outcome\.ok\) throw outcome\.error/);
  assert.match(videoWebhook, /return unwrapCallbackOutcome\(callbackOutcome\)/);
  assert.match(videoWebhook, /sentry_init_failed/);
  assert.match(videoWebhook, /typeof Sentry\.startSpan !== "function"/);
  assert.match(videoWebhook, /sentry_start_span_failed/);
  assert.match(videoWebhook, /void Sentry\.flush\(SENTRY_FLUSH_TIMEOUT_MS\)/);
  assert.match(videoWebhook, /sentry_capture_failed/);
  assert.match(videoWebhook, /webhook_trace_id/);
  assert.match(videoWebhook, /video_webhook_chat_vibe_clip_matched/);
  assert.match(videoWebhook, /client_request_id:\s+typeof chatClipUploadForLog\?\.client_request_id === "string"/);
  assert.match(videoWebhook, /provider_object_id: VideoGuid/);

  assert.match(chatVibeClipShared, /logChatVibeClipLifecycle/);
  assert.match(chatVibeClipShared, /message_ensure_started/);
  assert.match(chatVibeClipShared, /client_request_id: upload\.client_request_id/);
  assert.match(chatVibeClipShared, /provider_object_id: upload\.provider_object_id/);
  assert.match(chatVibeClipShared, /media_reference_created/);

  assert.match(getChatMediaUrl, /logChatMediaUrl/);
  assert.match(getChatMediaUrl, /stream_url_issued/);
  assert.match(getChatMediaUrl, /storage_proxy_token_issued/);
  assert.match(getChatMediaUrl, /client_request_id: clientRequestId/);
  assert.match(getChatMediaUrl, /provider_object_id: streamVideoId/);
  assert.doesNotMatch(getChatMediaUrl, /syncResult\.error/);
  assert.doesNotMatch(getChatMediaUrl, /userError\?\.message/);

  for (const source of [
    mediaLifecycleShared,
    uploadChatVideo,
    uploadImage,
    uploadVoice,
    uploadEventCover,
  ]) {
    assert.match(source, /@supabase\/supabase-js@2\.88\.0/);
  }
  assert.match(sendMessage, /SupabaseClient/);
  assert.match(sendGameEvent, /SupabaseClient/);
});
