-- Video Date single-owner runtime hardening.
--
-- The latest two-user production attempt reached both_ready, a canonical Daily
-- room, bilateral provider joins, and remote-media evidence, but the clients
-- churned across lobby/ready/date/survey while public RPCs still exposed raw
-- transport failures. Keep the core lifecycle bodies intact and make the public
-- boundary tolerant and auditable for web, native, and mobile web callers.

BEGIN;

CREATE TABLE IF NOT EXISTS public.video_date_surface_claim_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  session_id uuid NOT NULL,
  actor_id uuid,
  surface text NOT NULL,
  client_instance_id text,
  action text NOT NULL,
  takeover boolean NOT NULL DEFAULT false,
  ttl_seconds integer,
  ok boolean,
  blocked boolean,
  retryable boolean,
  result_code text,
  expires_at timestamptz,
  released_at timestamptz,
  detail jsonb NOT NULL DEFAULT '{}'::jsonb
);

ALTER TABLE public.video_date_surface_claim_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.video_date_surface_claim_events FROM PUBLIC, anon, authenticated;
GRANT ALL ON TABLE public.video_date_surface_claim_events TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.video_date_surface_claim_events_id_seq TO service_role;

CREATE INDEX IF NOT EXISTS idx_video_date_surface_claim_events_session_created
  ON public.video_date_surface_claim_events (session_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_video_date_surface_claim_events_actor_created
  ON public.video_date_surface_claim_events (actor_id, created_at DESC)
  WHERE actor_id IS NOT NULL;

COMMENT ON TABLE public.video_date_surface_claim_events IS
  'Append-only server-side audit for Video Date surface claim attempts and failures. Service-only by design; clients use claim_video_date_surface, not this table.';

DO $$
BEGIN
  IF to_regprocedure('public.video_date_transition_20260605232304_single_owner_base(uuid, text, text)') IS NULL
     AND to_regprocedure('public.video_date_transition(uuid, text, text)') IS NOT NULL THEN
    ALTER FUNCTION public.video_date_transition(uuid, text, text)
      RENAME TO video_date_transition_20260605232304_single_owner_base;
  END IF;

  IF to_regprocedure('public.get_video_date_queue_hint_v1_20260605232304_single_owner_base(uuid, uuid)') IS NULL
     AND to_regprocedure('public.get_video_date_queue_hint_v1(uuid, uuid)') IS NOT NULL THEN
    ALTER FUNCTION public.get_video_date_queue_hint_v1(uuid, uuid)
      RENAME TO get_video_date_queue_hint_v1_20260605232304_single_owner_base;
  END IF;

  IF to_regprocedure('public.drain_match_queue_v2_20260605232304_single_owner_base(uuid, text)') IS NULL
     AND to_regprocedure('public.drain_match_queue_v2(uuid, text)') IS NOT NULL THEN
    ALTER FUNCTION public.drain_match_queue_v2(uuid, text)
      RENAME TO drain_match_queue_v2_20260605232304_single_owner_base;
  END IF;

  IF to_regprocedure('public.claim_video_date_surface_20260605232304_single_owner_base(uuid, text, text, boolean, integer)') IS NULL
     AND to_regprocedure('public.claim_video_date_surface(uuid, text, text, boolean, integer)') IS NOT NULL THEN
    ALTER FUNCTION public.claim_video_date_surface(uuid, text, text, boolean, integer)
      RENAME TO claim_video_date_surface_20260605232304_single_owner_base;
  END IF;
END
$$;

REVOKE ALL ON FUNCTION public.video_date_transition_20260605232304_single_owner_base(uuid, text, text)
  FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.video_date_transition_20260605232304_single_owner_base(uuid, text, text)
  TO service_role;

REVOKE ALL ON FUNCTION public.get_video_date_queue_hint_v1_20260605232304_single_owner_base(uuid, uuid)
  FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.get_video_date_queue_hint_v1_20260605232304_single_owner_base(uuid, uuid)
  TO service_role;

REVOKE ALL ON FUNCTION public.drain_match_queue_v2_20260605232304_single_owner_base(uuid, text)
  FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.drain_match_queue_v2_20260605232304_single_owner_base(uuid, text)
  TO service_role;

REVOKE ALL ON FUNCTION public.claim_video_date_surface_20260605232304_single_owner_base(uuid, text, text, boolean, integer)
  FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.claim_video_date_surface_20260605232304_single_owner_base(uuid, text, text, boolean, integer)
  TO service_role;

CREATE OR REPLACE FUNCTION public.video_date_transition(
  p_session_id uuid,
  p_action text,
  p_reason text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public', 'pg_catalog'
AS $function$
DECLARE
  v_message text;
  v_detail text;
  v_hint text;
  v_server_now_ms bigint;
BEGIN
  RETURN public.video_date_transition_20260605232304_single_owner_base(
    p_session_id,
    p_action,
    p_reason
  );
EXCEPTION
  WHEN OTHERS THEN
    GET STACKED DIAGNOSTICS
      v_message = MESSAGE_TEXT,
      v_detail = PG_EXCEPTION_DETAIL,
      v_hint = PG_EXCEPTION_HINT;
    v_server_now_ms := floor(extract(epoch from clock_timestamp()) * 1000)::bigint;
    RETURN jsonb_build_object(
      'ok', false,
      'success', false,
      'error', 'video_date_transition_failed',
      'reason', 'video_date_transition_failed',
      'code', 'VIDEO_DATE_TRANSITION_FAILED',
      'error_code', 'VIDEO_DATE_TRANSITION_FAILED',
      'sqlstate', SQLSTATE,
      'message', v_message,
      'detail', NULLIF(v_detail, ''),
      'hint', NULLIF(v_hint, ''),
      'retryable', SQLSTATE IS DISTINCT FROM '42501',
      'retry_after_ms', 1500,
      'retry_after_seconds', 2,
      'server_now_ms', v_server_now_ms,
      'serverNowMs', v_server_now_ms
    );
END;
$function$;

CREATE OR REPLACE FUNCTION public.get_video_date_queue_hint_v1(
  p_event_id uuid,
  p_user_id uuid
)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path TO 'public', 'pg_catalog'
AS $function$
DECLARE
  v_message text;
  v_detail text;
  v_hint text;
BEGIN
  RETURN public.get_video_date_queue_hint_v1_20260605232304_single_owner_base(
    p_event_id,
    p_user_id
  );
EXCEPTION
  WHEN OTHERS THEN
    GET STACKED DIAGNOSTICS
      v_message = MESSAGE_TEXT,
      v_detail = PG_EXCEPTION_DETAIL,
      v_hint = PG_EXCEPTION_HINT;
    RETURN jsonb_build_object(
      'ok', false,
      'queued', false,
      'error', 'video_date_queue_hint_failed',
      'reason', 'video_date_queue_hint_failed',
      'code', 'VIDEO_DATE_QUEUE_HINT_FAILED',
      'error_code', 'VIDEO_DATE_QUEUE_HINT_FAILED',
      'sqlstate', SQLSTATE,
      'message', v_message,
      'detail', NULLIF(v_detail, ''),
      'hint', NULLIF(v_hint, ''),
      'retryable', SQLSTATE IS DISTINCT FROM '42501',
      'retry_after_ms', 1500,
      'event_queued_count', 0,
      'user_queued_count', 0,
      'position', NULL,
      'wait_age_seconds', 0,
      'estimated_wait_seconds', NULL,
      'relief_active', false
    );
END;
$function$;

CREATE OR REPLACE FUNCTION public.drain_match_queue_v2(
  p_event_id uuid,
  p_idempotency_key text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public', 'pg_catalog'
AS $function$
DECLARE
  v_message text;
  v_detail text;
  v_hint text;
  v_retryable boolean;
BEGIN
  RETURN public.drain_match_queue_v2_20260605232304_single_owner_base(
    p_event_id,
    p_idempotency_key
  );
EXCEPTION
  WHEN OTHERS THEN
    GET STACKED DIAGNOSTICS
      v_message = MESSAGE_TEXT,
      v_detail = PG_EXCEPTION_DETAIL,
      v_hint = PG_EXCEPTION_HINT;
    v_retryable := SQLSTATE IS DISTINCT FROM '42501';
    RETURN jsonb_build_object(
      'ok', false,
      'found', false,
      'success', false,
      'error', 'drain_match_queue_failed',
      'reason', 'drain_match_queue_failed',
      'code', 'DRAIN_MATCH_QUEUE_FAILED',
      'error_code', 'DRAIN_MATCH_QUEUE_FAILED',
      'commandStatus', CASE WHEN v_retryable THEN 'retryable_error' ELSE 'error' END,
      'sqlstate', SQLSTATE,
      'message', v_message,
      'detail', NULLIF(v_detail, ''),
      'hint', NULLIF(v_hint, ''),
      'retryable', v_retryable,
      'retry_after_ms', 1500
    );
END;
$function$;

CREATE OR REPLACE FUNCTION public.claim_video_date_surface(
  p_session_id uuid,
  p_surface text,
  p_client_instance_id text,
  p_takeover boolean DEFAULT false,
  p_ttl_seconds integer DEFAULT 12
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public', 'pg_catalog'
AS $function$
DECLARE
  v_actor uuid := auth.uid();
  v_result jsonb;
  v_message text;
  v_detail text;
  v_hint text;
  v_server_now_ms bigint;
BEGIN
  v_result := public.claim_video_date_surface_20260605232304_single_owner_base(
    p_session_id,
    p_surface,
    p_client_instance_id,
    p_takeover,
    p_ttl_seconds
  );

  BEGIN
    INSERT INTO public.video_date_surface_claim_events (
      session_id,
      actor_id,
      surface,
      client_instance_id,
      action,
      takeover,
      ttl_seconds,
      ok,
      blocked,
      retryable,
      result_code,
      detail
    ) VALUES (
      p_session_id,
      v_actor,
      public.video_date_client_stuck_safe_text(p_surface, 80),
      public.video_date_client_stuck_safe_text(p_client_instance_id, 160),
      'claim',
      COALESCE(p_takeover, false),
      CASE
        WHEN p_ttl_seconds IS NULL THEN NULL
        ELSE LEAST(3600, GREATEST(1, p_ttl_seconds))
      END,
      CASE lower(COALESCE(v_result->>'ok', ''))
        WHEN 'true' THEN true
        WHEN 'false' THEN false
        ELSE NULL
      END,
      CASE lower(COALESCE(v_result->>'blocked', ''))
        WHEN 'true' THEN true
        WHEN 'false' THEN false
        ELSE NULL
      END,
      CASE lower(COALESCE(v_result->>'retryable', ''))
        WHEN 'true' THEN true
        WHEN 'false' THEN false
        ELSE NULL
      END,
      public.video_date_client_stuck_safe_text(
        COALESCE(v_result->>'code', v_result->>'error_code', v_result->>'error', v_result->>'reason'),
        120
      ),
      jsonb_strip_nulls(jsonb_build_object(
        'result', v_result,
        'source', 'claim_video_date_surface'
      ))
    );
  EXCEPTION
    WHEN OTHERS THEN
      NULL;
  END;

  RETURN v_result;
EXCEPTION
  WHEN OTHERS THEN
    GET STACKED DIAGNOSTICS
      v_message = MESSAGE_TEXT,
      v_detail = PG_EXCEPTION_DETAIL,
      v_hint = PG_EXCEPTION_HINT;
    v_server_now_ms := floor(extract(epoch from clock_timestamp()) * 1000)::bigint;

    BEGIN
      INSERT INTO public.video_date_surface_claim_events (
        session_id,
        actor_id,
        surface,
        client_instance_id,
        action,
        takeover,
        ttl_seconds,
        ok,
        blocked,
        retryable,
        result_code,
        detail
      ) VALUES (
        p_session_id,
        v_actor,
        public.video_date_client_stuck_safe_text(p_surface, 80),
        public.video_date_client_stuck_safe_text(p_client_instance_id, 160),
        'claim_exception',
        COALESCE(p_takeover, false),
        CASE
          WHEN p_ttl_seconds IS NULL THEN NULL
          ELSE LEAST(3600, GREATEST(1, p_ttl_seconds))
        END,
        false,
        false,
        SQLSTATE IS DISTINCT FROM '42501',
        'SURFACE_CLAIM_FAILED',
        jsonb_strip_nulls(jsonb_build_object(
          'sqlstate', SQLSTATE,
          'message', v_message,
          'detail', NULLIF(v_detail, ''),
          'hint', NULLIF(v_hint, '')
        ))
      );
    EXCEPTION
      WHEN OTHERS THEN
        NULL;
    END;

    RETURN jsonb_build_object(
      'ok', false,
      'success', false,
      'error', 'surface_claim_failed',
      'code', 'SURFACE_CLAIM_FAILED',
      'error_code', 'SURFACE_CLAIM_FAILED',
      'sqlstate', SQLSTATE,
      'message', v_message,
      'detail', NULLIF(v_detail, ''),
      'hint', NULLIF(v_hint, ''),
      'retryable', SQLSTATE IS DISTINCT FROM '42501',
      'retry_after_ms', 1500,
      'server_now_ms', v_server_now_ms,
      'serverNowMs', v_server_now_ms
    );
END;
$function$;

CREATE OR REPLACE FUNCTION public.record_video_date_client_stuck_observability(
  p_session_id uuid,
  p_event_name text,
  p_payload jsonb DEFAULT '{}'::jsonb,
  p_latency_ms integer DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_actor uuid := auth.uid();
  v_session public.video_sessions%ROWTYPE;
  v_event_name text := lower(btrim(COALESCE(p_event_name, '')));
  v_payload jsonb := CASE
    WHEN jsonb_typeof(COALESCE(p_payload, '{}'::jsonb)) = 'object' THEN COALESCE(p_payload, '{}'::jsonb)
    ELSE '{}'::jsonb
  END;
  v_latency_ms integer;
  v_outcome text;
  v_detail jsonb;
  v_rowcnt integer := 0;
  v_append_only boolean := false;
BEGIN
  IF v_actor IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'unauthorized');
  END IF;

  IF v_event_name NOT IN (
    'ready_gate_handoff_slow',
    'prepare_date_entry_failed',
    'daily_join_confirmation_failed',
    'peer_missing_terminal',
    'peer_missing_suppressed_remote_seen',
    'peer_missing_suppressed_survey_truth',
    'daily_call_cleanup',
    'daily_call_reuse',
    'daily_call_busy_internal_retry',
    'remote_seen_canonical_repair_failed',
    'native_background_recovery_started',
    'native_background_recovery_failed',
    'native_background_expired'
  ) THEN
    RETURN jsonb_build_object('ok', false, 'error', 'unknown_event_name');
  END IF;

  SELECT *
  INTO v_session
  FROM public.video_sessions
  WHERE id = p_session_id;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('ok', false, 'error', 'session_not_found');
  END IF;

  IF v_session.participant_1_id IS DISTINCT FROM v_actor
     AND v_session.participant_2_id IS DISTINCT FROM v_actor THEN
    RETURN jsonb_build_object('ok', false, 'error', 'access_denied');
  END IF;

  v_latency_ms := CASE
    WHEN p_latency_ms IS NULL THEN NULL
    ELSE LEAST(86400000, GREATEST(0, p_latency_ms))
  END;

  v_append_only := v_event_name IN (
    'daily_call_cleanup',
    'daily_call_reuse',
    'daily_call_busy_internal_retry',
    'remote_seen_canonical_repair_failed'
  );

  v_outcome := CASE
    WHEN v_event_name IN (
      'prepare_date_entry_failed',
      'daily_join_confirmation_failed',
      'native_background_recovery_failed',
      'remote_seen_canonical_repair_failed'
    ) THEN 'failure'
    WHEN v_event_name IN (
      'ready_gate_handoff_slow',
      'peer_missing_terminal',
      'native_background_expired'
    ) THEN 'timeout'
    ELSE 'success'
  END;

  v_detail := jsonb_strip_nulls(jsonb_build_object(
    'client_event_name', v_event_name,
    'platform', CASE
      WHEN v_payload->>'platform' IN ('web', 'native') THEN v_payload->>'platform'
      ELSE NULL
    END,
    'source', public.video_date_client_stuck_safe_text(v_payload->>'source'),
    'source_surface', public.video_date_client_stuck_safe_text(v_payload->>'source_surface'),
    'source_action', public.video_date_client_stuck_safe_text(v_payload->>'source_action'),
    'reason_code', public.video_date_client_stuck_safe_text(v_payload->>'reason_code'),
    'code', public.video_date_client_stuck_safe_text(v_payload->>'code'),
    'phase', public.video_date_client_stuck_safe_text(v_payload->>'phase'),
    'room_name', public.video_date_client_stuck_safe_text(v_payload->>'room_name', 180),
    'caller', public.video_date_client_stuck_safe_text(v_payload->>'caller'),
    'meeting_state', public.video_date_client_stuck_safe_text(v_payload->>'meeting_state'),
    'cleanup_reason', public.video_date_client_stuck_safe_text(v_payload->>'cleanup_reason'),
    'latency_bucket', public.video_date_client_stuck_safe_text(v_payload->>'latency_bucket'),
    'entry_attempt_id', public.video_date_client_stuck_safe_text(v_payload->>'entry_attempt_id'),
    'daily_start_attempt_id', public.video_date_client_stuck_safe_text(v_payload->>'daily_start_attempt_id'),
    'video_date_trace_id', public.video_date_client_stuck_safe_text(v_payload->>'video_date_trace_id'),
    'singleton_parking_mode', public.video_date_client_stuck_safe_text(v_payload->>'singleton_parking_mode'),
    'attempt', public.video_date_client_stuck_safe_int(v_payload->>'attempt', 0, 100),
    'attempt_count', public.video_date_client_stuck_safe_int(v_payload->>'attempt_count', 0, 100),
    'elapsed_ms', public.video_date_client_stuck_safe_int(v_payload->>'elapsed_ms', 0, 86400000),
    'duration_ms', public.video_date_client_stuck_safe_int(v_payload->>'duration_ms', 0, 86400000),
    'grace_ms', public.video_date_client_stuck_safe_int(v_payload->>'grace_ms', 0, 86400000),
    'watchdog_ms', public.video_date_client_stuck_safe_int(v_payload->>'watchdog_ms', 0, 86400000),
    'auto_recovery_count', public.video_date_client_stuck_safe_int(v_payload->>'auto_recovery_count', 0, 100),
    'http_status', public.video_date_client_stuck_safe_int(v_payload->>'http_status', 100, 599),
    'truth_refresh_attempt', public.video_date_client_stuck_safe_int(v_payload->>'truth_refresh_attempt', 0, 100),
    'retryable', public.video_date_client_stuck_safe_bool(v_payload->>'retryable'),
    'exhausted', public.video_date_client_stuck_safe_bool(v_payload->>'exhausted'),
    'will_retry', public.video_date_client_stuck_safe_bool(v_payload->>'will_retry'),
    'leave_called', public.video_date_client_stuck_safe_bool(v_payload->>'leave_called'),
    'destroy_called', public.video_date_client_stuck_safe_bool(v_payload->>'destroy_called'),
    'reused', public.video_date_client_stuck_safe_bool(v_payload->>'reused'),
    'same_session_daily_continuity', public.video_date_client_stuck_safe_bool(v_payload->>'same_session_daily_continuity'),
    'same_session_daily_continuity_latched', public.video_date_client_stuck_safe_bool(v_payload->>'same_session_daily_continuity_latched'),
    'daily_call_singleton_eligible', public.video_date_client_stuck_safe_bool(v_payload->>'daily_call_singleton_eligible'),
    'will_park_singleton', public.video_date_client_stuck_safe_bool(v_payload->>'will_park_singleton'),
    'willParkSingleton', public.video_date_client_stuck_safe_bool(v_payload->>'willParkSingleton'),
    'parked_singleton', public.video_date_client_stuck_safe_bool(v_payload->>'parked_singleton'),
    'active_call_session_id_matches', public.video_date_client_stuck_safe_bool(v_payload->>'active_call_session_id_matches'),
    'route_owned', public.video_date_client_stuck_safe_bool(v_payload->>'route_owned'),
    'call_object_present', public.video_date_client_stuck_safe_bool(v_payload->>'call_object_present'),
    'historical_remote_seen_truth', public.video_date_client_stuck_safe_bool(v_payload->>'historical_remote_seen_truth'),
    'observed_at', now()
  ));

  IF v_append_only THEN
    INSERT INTO public.event_loop_observability_events (
      operation,
      outcome,
      reason_code,
      latency_ms,
      event_id,
      actor_id,
      session_id,
      detail
    ) VALUES (
      'video_date_client_stuck_state',
      v_outcome,
      v_event_name,
      v_latency_ms,
      v_session.event_id,
      v_actor,
      p_session_id,
      v_detail
    );
  ELSE
    INSERT INTO public.event_loop_observability_events (
      operation,
      outcome,
      reason_code,
      latency_ms,
      event_id,
      actor_id,
      session_id,
      detail
    ) VALUES (
      'video_date_client_stuck_state',
      v_outcome,
      v_event_name,
      v_latency_ms,
      v_session.event_id,
      v_actor,
      p_session_id,
      v_detail
    )
    ON CONFLICT (session_id, actor_id, operation, reason_code)
      WHERE operation = 'video_date_client_stuck_state'
        AND reason_code NOT IN (
          'daily_call_cleanup',
          'daily_call_reuse',
          'daily_call_busy_internal_retry',
          'remote_seen_canonical_repair_failed'
        )
      DO NOTHING;
  END IF;

  GET DIAGNOSTICS v_rowcnt = ROW_COUNT;

  RETURN jsonb_build_object(
    'ok', true,
    'inserted', v_rowcnt = 1,
    'deduped', v_rowcnt = 0
  );
EXCEPTION
  WHEN OTHERS THEN
    RETURN jsonb_build_object('ok', false, 'error', 'insert_failed');
END;
$function$;

REVOKE ALL ON FUNCTION public.video_date_transition(uuid, text, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.video_date_transition(uuid, text, text)
  TO authenticated, service_role;

REVOKE ALL ON FUNCTION public.get_video_date_queue_hint_v1(uuid, uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_video_date_queue_hint_v1(uuid, uuid)
  TO authenticated, service_role;

REVOKE ALL ON FUNCTION public.drain_match_queue_v2(uuid, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.drain_match_queue_v2(uuid, text)
  TO authenticated, service_role;

REVOKE ALL ON FUNCTION public.claim_video_date_surface(uuid, text, text, boolean, integer) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.claim_video_date_surface(uuid, text, text, boolean, integer)
  TO authenticated, service_role;

REVOKE ALL ON FUNCTION public.record_video_date_client_stuck_observability(uuid, text, jsonb, integer)
  FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.record_video_date_client_stuck_observability(uuid, text, jsonb, integer)
  TO authenticated;

COMMENT ON FUNCTION public.video_date_transition(uuid, text, text) IS
  'Canonical Video Date transition RPC. Outermost single-owner fail-soft wrapper: delegates to the current lifecycle base and returns structured JSON on uncaught backend errors.';

COMMENT ON FUNCTION public.get_video_date_queue_hint_v1(uuid, uuid) IS
  'Video Date queue hint RPC. Outermost single-owner fail-soft wrapper: queue-hint errors return structured nonqueued JSON instead of transport failure.';

COMMENT ON FUNCTION public.drain_match_queue_v2(uuid, text) IS
  'Video Date queue drain RPC. Outermost single-owner fail-soft wrapper: drain errors return structured retry guidance instead of transport failure.';

COMMENT ON FUNCTION public.claim_video_date_surface(uuid, text, text, boolean, integer) IS
  'Video Date surface claim RPC. Outermost single-owner fail-soft wrapper with append-only claim audit events for duplicate-tab/route-owner diagnosis.';

COMMENT ON FUNCTION public.record_video_date_client_stuck_observability(uuid, text, jsonb, integer) IS
  'Authenticated participant-only sparse client stuck-state audit ingestion for Video Date. Cleanup/reuse/remote-seen repair diagnostics are append-only and preserve single-owner Daily-route fields.';

NOTIFY pgrst, 'reload schema';

COMMIT;
