// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

type SupabaseViteEnv = {
  VITE_SUPABASE_URL?: string;
  VITE_SUPABASE_PUBLISHABLE_KEY?: string;
  VITE_SUPABASE_ANON_KEY?: string;
};

const viteEnv = (
  (import.meta as ImportMeta & { env?: SupabaseViteEnv }).env ?? {}
) as SupabaseViteEnv;
const isBrowser = typeof window !== "undefined";
const browserStorage =
  isBrowser &&
  typeof globalThis.localStorage?.getItem === "function" &&
  typeof globalThis.localStorage?.setItem === "function" &&
  typeof globalThis.localStorage?.removeItem === "function"
    ? globalThis.localStorage
    : undefined;

export const SUPABASE_URL = viteEnv.VITE_SUPABASE_URL ?? (isBrowser ? "" : "http://127.0.0.1:54321");
/** Prefer VITE_SUPABASE_PUBLISHABLE_KEY; fallback to VITE_SUPABASE_ANON_KEY for backward compatibility. */
export const SUPABASE_PUBLISHABLE_KEY =
  viteEnv.VITE_SUPABASE_PUBLISHABLE_KEY ?? viteEnv.VITE_SUPABASE_ANON_KEY ?? (isBrowser ? "" : "local-test-anon-key");

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: browserStorage,
    persistSession: isBrowser,
    autoRefreshToken: false,
    detectSessionInUrl: false,
    flowType: 'pkce',
  }
});
